# Phase 1: Exploration

## 1. Loading and inspecting the data

In [1]:
# Importing pandas and numpy to work as a dataframe

import pandas as pd
import numpy as np

In [2]:
# Displaying all rows

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
# Correcting the encoding (initially thought it was UTF-8 but detected a byte order mark)

df = pd.read_csv("97657-REG02_EPHC_1er Trim 2025.csv", encoding = 'utf-8-sig', sep = ';')

/var/folders/_2/rdn49_x54gj8wdryd0q1lxzr0000gn/T/ipykernel_5750/2743924195.py:3: DtypeWarning: Columns (144,151) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("97657-REG02_EPHC_1er Trim 2025.csv", encoding = 'utf-8-sig', sep = ';')

In [4]:
# How many rows and columns?

print('Shape: ', df.shape)

Shape:  (13246, 154)

In [5]:
# Column names

print("\nColumns: ", df.columns.tolist())

Columns:  ['UPM', 'NVIVI', 'NHOGA', 'TRIMESTRE', 'RONDA', 'ANIO', 'AREA', 'ESTGEO', 'L02', 'P02', 'P03', 'P06', 'P09', 'A01', 'A01A', 'A02', 'A03', 'A04', 'A04B', 'A04A', 'A05', 'A06', 'A06E', 'A07', 'A08', 'A09', 'A09E', 'A10', 'A11A', 'A11M', 'A11S', 'A12', 'A13REC', 'A14REC', 'A15', 'A16', 'A17A', 'A17M', 'A17S', 'A18', 'B01REC', 'B02REC', 'B03LU', 'B03MA', 'B03MI', 'B03JU', 'B03VI', 'B03SA', 'B03DO', 'B04', 'B05', 'B06', 'B07A', 'B07M', 'B07S', 'B08', 'B09A', 'B09M', 'B09S', 'B10', 'B11', 'B12', 'B13', 'B14', 'B15', 'B16G', 'B16U', 'B16D', 'B16T', 'B17', 'B18AG', 'B18AU', 'B18BG', 'B18BU', 'B19', 'B20G', 'B20U', 'B20D', 'B20T', 'B21', 'B22', 'B23', 'B24', 'B25', 'B26', 'B271', 'B272', 'B28', 'B29', 'B30', 'B31', 'C01REC', 'C02REC', 'C03', 'C04', 'C05', 'C06', 'C07', 'C08', 'C09', 'C101', 'C102', 'C11G', 'C11U', 'C11D', 'C11T', 'C12', 'C13AG', 'C13AU', 'C13BG', 'C13BU', 'C14', 'C14A', 'C14B', 'C14C', 'C15', 'C16REC', 'C17REC', 'C18', 'C18A', 'C18B', 'C19', 'D01', 'D02', 'D03', 'D04', 'D05', 'CATE_PEA', 'TAMA_PEA', 'OCUP_PEA', 'RAMA_PEA', 'HORAB', 'HORABC', 'HORABCO', 'PEAD', 'PEAD_1', 'PEAA', 'Factor', 'Añoest', 'Informalidad', 'E01AIMDE', 'E01BIMDE', 'E01CIMDE', 'E01DDE', 'E01EDE', 'E01FDE', 'E01GDE', 'E01HDE', 'E01IDE', 'E01JDE', 'E01KDE', 'E01LDE', 'E01MDE', 'E01KJDE']

In [6]:
# Type of columns. They're mostly codes so more numeric types expected.

print(df.dtypes)

UPM              int64
NVIVI            int64
NHOGA            int64
TRIMESTRE        int64
RONDA            int64
ANIO             int64
AREA             int64
ESTGEO           int64
L02              int64
P02              int64
P03              int64
P06              int64
P09              int64
A01             object
A01A            object
A02             object
A03             object
A04             object
A04B            object
A04A            object
A05             object
A06             object
A06E            object
A07             object
A08             object
A09             object
A09E            object
A10             object
A11A            object
A11M            object
A11S            object
A12             object
A13REC          object
A14REC          object
A15             object
A16             object
A17A            object
A17M            object
A17S            object
A18             object
B01REC          object
B02REC          object
B03LU           object
B03MA           object
B03MI           object
B03JU           object
B03VI           object
B03SA           object
B03DO           object
B04             object
B05             object
B06             object
B07A            object
B07M            object
B07S            object
B08             object
B09A            object
B09M            object
B09S            object
B10             object
B11             object
B12             object
B13             object
B14             object
B15             object
B16G            object
B16U            object
B16D            object
B16T            object
B17             object
B18AG           object
B18AU           object
B18BG           object
B18BU           object
B19             object
B20G            object
B20U            object
B20D            object
B20T            object
B21             object
B22             object
B23             object
B24             object
B25             object
B26             object
B271            object
B272            object
B28             object
B29             object
B30             object
B31             object
C01REC          object
C02REC          object
C03             object
C04             object
C05             object
C06             object
C07             object
C08             object
C09             object
C101            object
C102            object
C11G            object
C11U            object
C11D            object
C11T            object
C12             object
C13AG           object
C13AU           object
C13BG           object
C13BU           object
C14             object
C14A            object
C14B            object
C14C            object
C15             object
C16REC          object
C17REC          object
C18             object
C18A            object
C18B            object
C19             object
D01             object
D02             object
D03             object
D04             object
D05             object
CATE_PEA        object
TAMA_PEA        object
OCUP_PEA        object
RAMA_PEA        object
HORAB           object
HORABC          object
HORABCO         object
PEAD            object
PEAD_1          object
PEAA            object
Factor           int64
Añoest          object
Informalidad    object
E01AIMDE        object
E01BIMDE        object
E01CIMDE        object
E01DDE          object
E01EDE          object
E01FDE          object
E01GDE          object
E01HDE          object
E01IDE          object
E01JDE          object
E01KDE          object
E01LDE          object
E01MDE          object
E01KJDE         object
dtype: object

In [7]:
# Viewing the first rows to see structure

print("\nFirst 5 rows: ")
print(df.head())

First 5 rows:
   UPM  NVIVI  NHOGA  TRIMESTRE  RONDA  ANIO  AREA  ESTGEO  L02  P02  P03  \
0   14     13      1         13      1  2025     1       1    1   65    1
1   14     13      1         13      1  2025     1       1    2   69    2
2   14     15      1         13      2  2025     1       1    1   78    1
3   14     15      1         13      2  2025     1       1    2   78    2
4   14     16      1         13      1  2025     1       1    1   40    1

   P06  P09 A01 A01A A02 A03 A04 A04B A04A A05 A06 A06E A07 A08 A09 A09E A10  \
0    1    1   1        6   6   6             1            6   6  15
1    6    1   6    1   1                 1
2    1    1   1        6   6   6             6   6
3    6    1   6    1   6   6   6             6   5
4    1    2   1        1                 1

  A11A A11M A11S A12 A13REC A14REC A15 A16 A17A A17M A17S A18 B01REC B02REC  \
0                  1      3      2   2   8    3    0    0   8
1                                                                  2      8
2                  1      7      4   4   1   10    0    0  15
3                  1      7      5   4   1   20    0    0  17
4                                                                  3      2

  B03LU B03MA B03MI B03JU B03VI B03SA B03DO B04 B05 B06 B07A B07M B07S B08  \
0
1     8     8     8     8     8     8     8   2      48   50    0    0   6
2
3
4     9     9     9     9     9     0     0   1            7    0    0   8

  B09A B09M B09S B10 B11 B12 B13 B14 B15         B16G B16U B16D         B16T  \
0
1   20    0    0   1   1   2  12   1   4  99999999999    5       99999999999
2
3
4    7    0    0   1   1   2  18   2   4      4500000    5           4500000

  B17 B18AG B18AU    B18BG B18BU B19 B20G B20U B20D B20T B21 B22 B23 B24 B25  \
0
1   6                              6                       6           6
2
3
4   1     0        4500000     6   6                       6           6

  B26 B271 B272 B28 B29 B30 B31 C01REC C02REC C03 C04 C05 C06 C07 C08 C09  \
0
1   1             1   2   1   6
2
3
4   3             1   2   1   6

  C101 C102 C11G C11U C11D C11T C12 C13AG C13AU C13BG C13BU C14 C14A C14B  \
0
1
2
3
4

  C14C C15 C16REC C17REC C18 C18A C18B C19 D01 D02 D03 D04 D05 CATE_PEA  \
0
1                                            6       1       3        2
2
3
4                                            6       6                2

  TAMA_PEA OCUP_PEA RAMA_PEA HORAB HORABC HORABCO PEAD PEAD_1 PEAA  Factor  \
0                                                    3      3    3     381
1        6        2        8    48     48      48    1      1    1     381
2                                                    3      3    3     469
3                                                    3      3    3     469
4        8        3        2    45     45      45    1      1    1     708

  Añoest Informalidad     E01AIMDE E01BIMDE E01CIMDE       E01DDE E01EDE  \
0     15                         0        0        0  6026470,588      0
1     18            2  7066529,033        0        0            0      0
2      6                         0        0        0            0      0
3     12                         0        0        0            0      0
4     17            2  4519852,941        0        0            0      0

        E01FDE E01GDE       E01HDE E01IDE E01JDE E01KDE E01LDE E01MDE E01KJDE
0            0      0  6026470,588      0      0      0      0      0       0
1            0      0            0      0      0      0      0      0       0
2  3093588,235      0            0      0      0      0      0      0       0
3            0      0            0      0      0      0      0      0       0
4            0      0            0      0      0      0      0      0       0

In [8]:
# Verifying missing values, none initially, so missing values are coded with something else that's not NaN.

print("\nMissing values per column:")
print(df.isnull().sum().sort_values(ascending = False))

Missing values per column:
UPM             0
C11T            0
C08             0
C09             0
C101            0
C102            0
C11G            0
C11U            0
C11D            0
C12             0
C15             0
C13AG           0
C13AU           0
C13BG           0
C13BU           0
C14             0
C14A            0
C14B            0
C07             0
C06             0
C05             0
C04             0
B21             0
B22             0
B23             0
B24             0
B25             0
B26             0
B271            0
B272            0
B28             0
B29             0
B30             0
B31             0
C01REC          0
C02REC          0
C03             0
C14C            0
C16REC          0
NVIVI           0
E01EDE          0
Factor          0
Añoest          0
Informalidad    0
E01AIMDE        0
E01BIMDE        0
E01CIMDE        0
E01DDE          0
E01FDE          0
C17REC          0
E01GDE          0
E01HDE          0
E01IDE          0
E01JDE          0
E01KDE          0
E01LDE          0
E01MDE          0
PEAA            0
PEAD_1          0
PEAD            0
HORABCO         0
C18             0
C18A            0
C18B            0
C19             0
D01             0
D02             0
D03             0
D04             0
D05             0
CATE_PEA        0
TAMA_PEA        0
OCUP_PEA        0
RAMA_PEA        0
HORAB           0
HORABC          0
B20T            0
B20D            0
B20U            0
A11A            0
A06             0
A06E            0
A07             0
A08             0
A09             0
A09E            0
A10             0
A11M            0
B20G            0
A11S            0
A12             0
A13REC          0
A14REC          0
A15             0
A16             0
A17A            0
A05             0
A04A            0
A04B            0
A04             0
NHOGA           0
TRIMESTRE       0
RONDA           0
ANIO            0
AREA            0
ESTGEO          0
L02             0
P02             0
P03             0
P06             0
P09             0
A01             0
A01A            0
A02             0
A03             0
A17M            0
A17S            0
A18             0
B09S            0
B11             0
B12             0
B13             0
B14             0
B15             0
B16G            0
B16U            0
B16D            0
B16T            0
B17             0
B18AG           0
B18AU           0
B18BG           0
B18BU           0
B19             0
B10             0
B09M            0
B01REC          0
B09A            0
B02REC          0
B03LU           0
B03MA           0
B03MI           0
B03JU           0
B03VI           0
B03SA           0
B03DO           0
B04             0
B05             0
B06             0
B07A            0
B07M            0
B07S            0
B08             0
E01KJDE         0
dtype: int64

In [9]:
# Viewing descriptive statistics of numeric columns.

print(df.describe())

                UPM         NVIVI         NHOGA  TRIMESTRE         RONDA  \
count  13246.000000  13246.000000  13246.000000    13246.0  13246.000000
mean   15117.730183     34.766571      1.000302       13.0      1.493658
std     8676.860203     24.194281      0.017376        0.0      0.499979
min       14.000000      1.000000      1.000000       13.0      1.000000
25%     7593.000000     16.000000      1.000000       13.0      1.000000
50%    14950.000000     32.000000      1.000000       13.0      1.000000
75%    22324.000000     49.000000      1.000000       13.0      2.000000
max    28724.000000    198.000000      2.000000       13.0      2.000000

          ANIO          AREA        ESTGEO           L02           P02  \
count  13246.0  13246.000000  13246.000000  13246.000000  13246.000000
mean    2025.0      3.058735     82.399668      2.709497     33.567341
std        0.0      2.460842     43.659688      1.745882     22.122773
min     2025.0      1.000000      1.000000      1.000000      0.000000
25%     2025.0      1.000000     46.000000      1.000000     15.000000
50%     2025.0      1.000000     96.000000      2.000000     31.000000
75%     2025.0      6.000000    111.000000      4.000000     50.000000
max     2025.0      6.000000    156.000000     20.000000    104.000000

                P03           P06           P09        Factor
count  13246.000000  13246.000000  13246.000000  13246.000000
mean       2.692737      3.532463      3.441945    464.595501
std        1.856283      2.499884      1.729081    332.550040
min        1.000000      1.000000      1.000000     33.000000
25%        1.000000      1.000000      2.000000    223.000000
50%        3.000000      6.000000      5.000000    378.000000
75%        3.000000      6.000000      5.000000    618.000000
max       12.000000      6.000000      6.000000   4734.000000

## 2. Derive department from ESTGEO and build department name mapping

In [10]:
# Verifying vs. dictionary which departments are covered.
# The dataset covers 17 of Paraguay's 18 administrative units — Boquerón is not represented in the Q1 2025 EPHC sample.

print(df['ESTGEO'].unique())

[  1  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86  91
  96 101 106 111 116 121 126 131 136 141 146 151 156]

In [11]:
# Creating new column based on the first digit of the ESTGEO. Last two digits indicates rural or urban zone of the department.
# 0 for Asuncion.

df['DPTO'] = df['ESTGEO'].apply(lambda x: 0 if x == 1 else x // 10)
print(df['DPTO'].value_counts().sort_index())

DPTO
0      963
1      504
2      622
3      746
4      602
5      689
6      547
7      947
8      723
9      591
10    1519
11    2389
12     445
13     581
14     790
15     588
Name: count, dtype: int64

Mapping 0–15 to the department names based on the ESTGEO codes and applying to df as a new column.

In [12]:
# Mapping department names to their corresponding codes.

dpto_names = {
    0: 'Asunción',
    1: 'Concepción',
    2: 'San Pedro',
    3: 'Cordillera',
    4: 'Guairá',
    5: 'Caaguazú',
    6: 'Caazapá',
    7: 'Itapúa',
    8: 'Misiones',
    9: 'Paraguarí',
    10: 'Alto Paraná',
    11: 'Central',
    12: 'Ñeembucú',
    13: 'Amambay',
    14: 'Canindeyú',
    15: 'Pdte Hayes'
}

df['DPTO_NAMES'] = df['DPTO'].map(dpto_names)

In [13]:
# Verifying the first rows with the changes applied.

df.head(20)

,UPM,NVIVI,NHOGA,TRIMESTRE,RONDA,ANIO,AREA,ESTGEO,L02,P02,P03,P06,P09,A01,A01A,A02,A03,A04,A04B,A04A,A05,A06,A06E,A07,A08,A09,A09E,A10,A11A,A11M,A11S,A12,A13REC,A14REC,A15,A16,A17A,A17M,A17S,A18,B01REC,B02REC,B03LU,B03MA,B03MI,B03JU,B03VI,B03SA,B03DO,B04,B05,B06,B07A,B07M,B07S,B08,B09A,B09M,B09S,B10,B11,B12,B13,B14,B15,B16G,B16U,B16D,B16T,B17,B18AG,B18AU,B18BG,B18BU,B19,B20G,B20U,B20D,B20T,B21,B22,B23,B24,B25,B26,B271,B272,B28,B29,B30,B31,C01REC,C02REC,C03,C04,C05,C06,C07,C08,C09,C101,C102,C11G,C11U,C11D,C11T,C12,C13AG,C13AU,C13BG,C13BU,C14,C14A,C14B,C14C,C15,C16REC,C17REC,C18,C18A,C18B,C19,D01,D02,D03,D04,D05,CATE_PEA,TAMA_PEA,OCUP_PEA,RAMA_PEA,HORAB,HORABC,HORABCO,PEAD,PEAD_1,PEAA,Factor,Añoest,Informalidad,E01AIMDE,E01BIMDE,E01CIMDE,E01DDE,E01EDE,E01FDE,E01GDE,E01HDE,E01IDE,E01JDE,E01KDE,E01LDE,E01MDE,E01KJDE,DPTO,DPTO_NAMES
0,14,13,1,13,1,2025,1,1,1,65,1,1,1,1,,6,6,6,,,1,,,6,6,15,,,,,,1,3,2,2,8,3,0,0,8,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,3,3,381,15,,0,0,0,"6026470,588",0,0,0,"6026470,588",0,0,0,0,0,0,0,Asunción
1,14,13,1,13,1,2025,1,1,2,69,2,6,1,6,1,1,,,,1,,,,,,,,,,,,,,,,,,,,,2,8,8,8,8,8,8,8,8,2,,48,50,0,0,6,20,0,0,1,1,2,12,1,4,99999999999,5,,99999999999,6,,,,,6,,,,,6,,,6,,1,,,1,2,1,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,1,,3,2,6,2,8,48,48,48,1,1,1,381,18,2,"7066529,033",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
2,14,15,1,13,2,2025,1,1,1,78,1,1,1,1,,6,6,6,,,6,6,,,,,,,,,,1,7,4,4,1,10,0,0,15,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,3,3,469,6,,0,0,0,0,0,"3093588,235",0,0,0,0,0,0,0,0,0,Asunción
3,14,15,1,13,2,2025,1,1,2,78,2,6,1,6,1,6,6,6,,,6,5,,,,,,,,,,1,7,5,4,1,20,0,0,17,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,3,3,469,12,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
4,14,16,1,13,1,2025,1,1,1,40,1,1,2,1,,1,,,,1,,,,,,,,,,,,,,,,,,,,,3,2,9,9,9,9,9,0,0,1,,,7,0,0,8,7,0,0,1,1,2,18,2,4,4500000,5,,4500000,1,0,,4500000,6,6,,,,,6,,,6,,3,,,1,2,1,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,6,,,2,8,3,2,45,45,45,1,1,1,708,17,2,"4519852,941",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
5,14,16,1,13,1,2025,1,1,2,39,2,6,2,6,1,1,,,,1,,,,,,,,,,,,,,,,,,,,,5,8,7,7,7,7,7,7,0,1,,,6,0,0,1,3,0,0,6,,4,,,,,,,,,,,,,,,,,,,,,,,,2,,6,,6,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,6,,,4,1,5,8,42,42,42,1,1,1,708,14,1,"5022058,824",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
6,14,16,1,13,1,2025,1,1,3,19,3,6,5,6,1,6,6,6,,,6,4,,,,,,,,,,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,3,3,708,12,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
7,14,26,1,13,2,2025,1,1,1,32,1,1,5,1,,1,,,,1,,,,,,,,,,,,,,,,,,,,,8,2,8,8,8,8,8,8,8,1,,,8,0,0,7,8,0,0,1,1,2,30,88,4,3200000,5,,3200000,6,,,,,6,,,,,6,,,1,200000,1,,,1,2,1,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,6,,,2,7,8,2,56,56,56,1,1,1,723,12,2,"3214117,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
8,14,26,1,13,2,2025,1,1,2,34,9,1,5,6,1,1,,,,1,,,,,,,,,,,,,,,,,,,,,2,8,8,8,8,8,8,0,0,1,,,8,0,0,11,8,0,0,1,2,1,30,2,4,4000000,5,,4000000,6,,,,,6,,,,,6,,,6,,1,,,,,,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,6,,,1,11,2,8,40,40,40,1,1,1,723,17,2,"4017647,059",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
9,14,35,1,13,1,2025,1,1,1,24,1,1,2,1,,1,,,,1,,,,,,,,,,,,,,,,,,,,,5,5,0,8,8,12,12,12,12,1,,,8,0,0,2,0,2,0,6,,2,88,1,4,2500000,5,,2500000,1,500000,5,300000,6,1,800000,5,,800000,6,,,1,140000,4,,,1,1,1,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,6,,,2,2,5,5,64,64,64,1,1,1,437,12,1,"3816764,706",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
10,14,35,1,13,1,2025,1,1,2,27,2,6,2,1,,1,,,,1,,,,,,,,,,,,,,,,,,,,,9,5,8,0,8,10,10,6,6,1,,,4,0,0,7,4,0,0,1,1,2,12,1,4,2800000,5,,2800000,1,180000,5,2800000,6,6,,,,,6,,,6,,3,,,1,2,1,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,6,,,2,7,9,5,48,48,48,1,1,1,437,13,2,"2993147,059",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
11,14,47,1,13,1,2025,1,1,1,40,1,1,3,1,,1,,,,1,,,,,,,,,,,,,,,,,,,,,5,8,18,0,18,18,0,0,18,1,,,18,0,0,8,18,0,0,1,2,1,30,3,4,5000000,5,,5000000,1,110000,5,5000000,6,1,300000,5,,300000,6,,,6,,1,,,,,,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,6,,,1,8,5,8,72,72,72,1,1,1,697,13,2,"5433867,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
12,14,50,1,13,1,2025,1,1,1,63,1,6,5,1,,6,6,6,,,1,,,6,6,15,,,,,,1,2,8,1,7,10,0,0,8,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,3,3,405,18,,0,0,0,0,0,0,0,"5524264,706",0,0,0,0,0,0,0,Asunción
13,14,57,1,13,2,2025,1,1,1,71,1,1,1,6,3,6,6,6,,,6,9,,,,,,,,,,1,3,8,1,7,11,0,0,8,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,3,3,778,12,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
14,14,57,1,13,2,2025,1,1,2,76,2,6,1,6,3,6,6,6,,,6,3,,,,,,,,,,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,3,3,778,12,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
15,14,57,1,13,2,2025,1,1,3,46,3,1,5,1,,1,,,,1,,,,,,,,,,,,,,,,,,,,,5,5,12,12,12,12,12,12,5,1,,,25,0,0,2,25,0,0,6,,4,,,,,,,,,,,,,,,,,,,,,,,,3,,1,1,1,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,20,2,6,10,4,2,5,5,77,77,77,1,1,1,778,12,2,"1305735,294",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
16,14,57,1,13,2,2025,1,1,4,42,3,6,5,6,3,1,,,,1,,,,,,,,,,,,,,,,,,,,,5,5,12,12,12,12,12,12,5,1,,,25,0,0,2,25,0,0,6,,5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,30,2,6,7,5,2,5,5,77,77,77,1,1,1,778,17,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
17,14,66,1,13,2,2025,1,1,1,31,1,1,3,1,,1,,,,1,,,,,,,,,,,,,,,,,,,,,3,8,"5,3","5,3","5,3","5,3","5,3",0,0,1,,,13,0,0,4,13,0,0,6,,2,88,2,4,10000000,5,,10000000,6,,,,,6,,,,,6,,,6,,2,,,1,5,1,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,10,2,1,11,2,4,3,8,28,28,28,4,4,1,676,16,1,"10044117,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
18,14,66,1,13,2,2025,1,1,4,26,9,6,5,6,1,1,,,,1,,,,,,,,,,,,,,,,,,,,,3,8,1,1,1,1,1,0,0,1,,,1,0,0,11,1,0,0,6,,2,12,2,4,1750000,5,,1750000,6,,,,,6,,,,,6,,,6,,4,,,1,5,1,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6,,6,,,2,11,3,8,5,5,5,1,1,1,676,17,1,"1757720,588",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
19,14,66,1,13,2,2025,1,1,5,10,9,1,5,6,1,6,6,6,,,6,4,,,,,,,,,,6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,3,3,676,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción

In [14]:
# Checking if there are no NaN values in DPTO_NAMES

df['DPTO_NAMES'].isnull().sum()

np.int64(0)

In [15]:
# Grouping columns E... to verify amount of 0s to correct to NaN.

income_df = df.loc[:, 'E01AIMDE': 'E01KJDE']

for col_name in income_df.columns:
    print(f"Column name: {col_name}")
    print(df[col_name][df[col_name] == '0'].value_counts())
    print("\n")

Column name: E01AIMDE
E01AIMDE
0    7099
Name: count, dtype: int64


Column name: E01BIMDE
E01BIMDE
0    12663
Name: count, dtype: int64


Column name: E01CIMDE
E01CIMDE
0    13209
Name: count, dtype: int64


Column name: E01DDE
E01DDE
0    13080
Name: count, dtype: int64


Column name: E01EDE
E01EDE
0    12279
Name: count, dtype: int64


Column name: E01FDE
E01FDE
0    12604
Name: count, dtype: int64


Column name: E01GDE
E01GDE
0    13009
Name: count, dtype: int64


Column name: E01HDE
E01HDE
0    12958
Name: count, dtype: int64


Column name: E01IDE
E01IDE
0    12903
Name: count, dtype: int64


Column name: E01JDE
E01JDE
0    13186
Name: count, dtype: int64


Column name: E01KDE
E01KDE
0    12446
Name: count, dtype: int64


Column name: E01LDE
E01LDE
0    4095
Name: count, dtype: int64


Column name: E01MDE
E01MDE
0    13101
Name: count, dtype: int64


Column name: E01KJDE
E01KJDE
0    12886
Name: count, dtype: int64

## Columns cleaning block

In [16]:
# Stripping all cells from unnecessary whitepaces for all strings.

df = df.map(lambda x: x.strip() if isinstance(x, str) else x)

# Replacing df with df adjusted - Use map to change every single cell in the dataframe - lambda x is a temporary function writer - strip() is for stripping unnecessary whitespaces - isinstance checks type - otherwise just return x

In [17]:
# Replacing all whitespaces with NaN values.

df = df.replace(r'^\s*$', np.nan, regex=True)
df.head(20)

/var/folders/_2/rdn49_x54gj8wdryd0q1lxzr0000gn/T/ipykernel_5750/4095802408.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r'^\s*$', np.nan, regex=True)

,UPM,NVIVI,NHOGA,TRIMESTRE,RONDA,ANIO,AREA,ESTGEO,L02,P02,P03,P06,P09,A01,A01A,A02,A03,A04,A04B,A04A,A05,A06,A06E,A07,A08,A09,A09E,A10,A11A,A11M,A11S,A12,A13REC,A14REC,A15,A16,A17A,A17M,A17S,A18,B01REC,B02REC,B03LU,B03MA,B03MI,B03JU,B03VI,B03SA,B03DO,B04,B05,B06,B07A,B07M,B07S,B08,B09A,B09M,B09S,B10,B11,B12,B13,B14,B15,B16G,B16U,B16D,B16T,B17,B18AG,B18AU,B18BG,B18BU,B19,B20G,B20U,B20D,B20T,B21,B22,B23,B24,B25,B26,B271,B272,B28,B29,B30,B31,C01REC,C02REC,C03,C04,C05,C06,C07,C08,C09,C101,C102,C11G,C11U,C11D,C11T,C12,C13AG,C13AU,C13BG,C13BU,C14,C14A,C14B,C14C,C15,C16REC,C17REC,C18,C18A,C18B,C19,D01,D02,D03,D04,D05,CATE_PEA,TAMA_PEA,OCUP_PEA,RAMA_PEA,HORAB,HORABC,HORABCO,PEAD,PEAD_1,PEAA,Factor,Añoest,Informalidad,E01AIMDE,E01BIMDE,E01CIMDE,E01DDE,E01EDE,E01FDE,E01GDE,E01HDE,E01IDE,E01JDE,E01KDE,E01LDE,E01MDE,E01KJDE,DPTO,DPTO_NAMES
0,14,13,1,13,1,2025,1,1,1,65,1,1,1,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,3,2,2,8,3,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,381,15,NaN,0,0,0,"6026470,588",0,0,0,"6026470,588",0,0,0,0,0,0,0,Asunción
1,14,13,1,13,1,2025,1,1,2,69,2,6,1,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,8,8,2,NaN,48,50,0,0,6,20,0,0,1,1,2,12,1,4,99999999999,5,NaN,99999999999,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,3,2,6,2,8,48,48,48,1,1,1,381,18,2,"7066529,033",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
2,14,15,1,13,2,2025,1,1,1,78,1,1,1,1,NaN,6,6,6,NaN,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,4,4,1,10,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,6,NaN,0,0,0,0,0,"3093588,235",0,0,0,0,0,0,0,0,0,Asunción
3,14,15,1,13,2,2025,1,1,2,78,2,6,1,6,1,6,6,6,NaN,NaN,6,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,5,4,1,20,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,12,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
4,14,16,1,13,1,2025,1,1,1,40,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,9,9,9,9,9,0,0,1,NaN,NaN,7,0,0,8,7,0,0,1,1,2,18,2,4,4500000,5,NaN,4500000,1,0,NaN,4500000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,8,3,2,45,45,45,1,1,1,708,17,2,"4519852,941",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
5,14,16,1,13,1,2025,1,1,2,39,2,6,2,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,7,7,7,7,7,7,0,1,NaN,NaN,6,0,0,1,3,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,6,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,4,1,5,8,42,42,42,1,1,1,708,14,1,"5022058,824",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
6,14,16,1,13,1,2025,1,1,3,19,3,6,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,708,12,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
7,14,26,1,13,2,2025,1,1,1,32,1,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2,8,8,8,8,8,8,8,1,NaN,NaN,8,0,0,7,8,0,0,1,1,2,30,88,4,3200000,5,NaN,3200000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,1,200000,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,8,2,56,56,56,1,1,1,723,12,2,"3214117,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
8,14,26,1,13,2,2025,1,1,2,34,9,1,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,0,0,1,NaN,NaN,8,0,0,11,8,0,0,1,2,1,30,2,4,4000000,5,NaN,4000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,11,2,8,40,40,40,1,1,1,723,17,2,"4017647,059",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
9,14,35,1,13,1,2025,1,1,1,24,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,0,8,8,12,12,12,12,1,NaN,NaN,8,0,0,2,0,2,0,6,NaN,2,88,1,4,2500000,5,NaN,2500000,1,500000,5,300000,6,1,800000,5,NaN,800000,6,NaN,NaN,1,140000,4,NaN,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,2,5,5,64,64,64,1,1,1,437,12,1,"3816764,706",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
10,14,35,1,13,1,2025,1,1,2,27,2,6,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,5,8,0,8,10,10,6,6,1,NaN,NaN,4,0,0,7,4,0,0,1,1,2,12,1,4,2800000,5,NaN,2800000,1,180000,5,2800000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,9,5,48,48,48,1,1,1,437,13,2,"2993147,059",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
11,14,47,1,13,1,2025,1,1,1,40,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,18,0,18,18,0,0,18,1,NaN,NaN,18,0,0,8,18,0,0,1,2,1,30,3,4,5000000,5,NaN,5000000,1,110000,5,5000000,6,1,300000,5,NaN,300000,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,8,5,8,72,72,72,1,1,1,697,13,2,"5433867,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
12,14,50,1,13,1,2025,1,1,1,63,1,6,5,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,2,8,1,7,10,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,405,18,NaN,0,0,0,0,0,0,0,"5524264,706",0,0,0,0,0,0,0,Asunción
13,14,57,1,13,2,2025,1,1,1,71,1,1,1,6,3,6,6,6,NaN,NaN,6,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,8,1,7,11,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
14,14,57,1,13,2,2025,1,1,2,76,2,6,1,6,3,6,6,6,NaN,NaN,6,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
15,14,57,1,13,2,2025,1,1,3,46,3,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,20,2,6,10,4,2,5,5,77,77,77,1,1,1,778,12,2,"1305735,294",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
16,14,57,1,13,2,2025,1,1,4,42,3,6,5,6,3,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,30,2,6,7,5,2,5,5,77,77,77,1,1,1,778,17,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
17,14,66,1,13,2,2025,1,1,1,31,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,"5,3","5,3","5,3","5,3","5,3",0,0,1,NaN,NaN,13,0,0,4,13,0,0,6,NaN,2,88,2,4,10000000,5,NaN,10000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,2,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,2,1,11,2,4,3,8,28,28,28,4,4,1,676,16,1,"10044117,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
18,14,66,1,13,2,2025,1,1,4,26,9,6,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,1,1,1,1,1,0,0,1,NaN,NaN,1,0,0,11,1,0,0,6,NaN,2,12,2,4,1750000,5,NaN,1750000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,4,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,11,3,8,5,5,5,1,1,1,676,17,1,"1757720,588",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
19,14,66,1,13,2,2025,1,1,5,10,9,1,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,676,2,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción

In [18]:
# Replacing all sentinel values with NaN as well.

df = df.replace('99999999999', np.nan, regex=True)
df.head(20)

/var/folders/_2/rdn49_x54gj8wdryd0q1lxzr0000gn/T/ipykernel_5750/1951262663.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('99999999999', np.nan, regex=True)

,UPM,NVIVI,NHOGA,TRIMESTRE,RONDA,ANIO,AREA,ESTGEO,L02,P02,P03,P06,P09,A01,A01A,A02,A03,A04,A04B,A04A,A05,A06,A06E,A07,A08,A09,A09E,A10,A11A,A11M,A11S,A12,A13REC,A14REC,A15,A16,A17A,A17M,A17S,A18,B01REC,B02REC,B03LU,B03MA,B03MI,B03JU,B03VI,B03SA,B03DO,B04,B05,B06,B07A,B07M,B07S,B08,B09A,B09M,B09S,B10,B11,B12,B13,B14,B15,B16G,B16U,B16D,B16T,B17,B18AG,B18AU,B18BG,B18BU,B19,B20G,B20U,B20D,B20T,B21,B22,B23,B24,B25,B26,B271,B272,B28,B29,B30,B31,C01REC,C02REC,C03,C04,C05,C06,C07,C08,C09,C101,C102,C11G,C11U,C11D,C11T,C12,C13AG,C13AU,C13BG,C13BU,C14,C14A,C14B,C14C,C15,C16REC,C17REC,C18,C18A,C18B,C19,D01,D02,D03,D04,D05,CATE_PEA,TAMA_PEA,OCUP_PEA,RAMA_PEA,HORAB,HORABC,HORABCO,PEAD,PEAD_1,PEAA,Factor,Añoest,Informalidad,E01AIMDE,E01BIMDE,E01CIMDE,E01DDE,E01EDE,E01FDE,E01GDE,E01HDE,E01IDE,E01JDE,E01KDE,E01LDE,E01MDE,E01KJDE,DPTO,DPTO_NAMES
0,14,13,1,13,1,2025,1,1,1,65,1,1,1,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,3,2,2,8,3,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,381,15,NaN,0,0,0,"6026470,588",0,0,0,"6026470,588",0,0,0,0,0,0,0,Asunción
1,14,13,1,13,1,2025,1,1,2,69,2,6,1,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,8,8,2,NaN,48,50,0,0,6,20,0,0,1,1,2,12,1,4,NaN,5,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,3,2,6,2,8,48,48,48,1,1,1,381,18,2,"7066529,033",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
2,14,15,1,13,2,2025,1,1,1,78,1,1,1,1,NaN,6,6,6,NaN,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,4,4,1,10,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,6,NaN,0,0,0,0,0,"3093588,235",0,0,0,0,0,0,0,0,0,Asunción
3,14,15,1,13,2,2025,1,1,2,78,2,6,1,6,1,6,6,6,NaN,NaN,6,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,5,4,1,20,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,12,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
4,14,16,1,13,1,2025,1,1,1,40,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,9,9,9,9,9,0,0,1,NaN,NaN,7,0,0,8,7,0,0,1,1,2,18,2,4,4500000,5,NaN,4500000,1,0,NaN,4500000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,8,3,2,45,45,45,1,1,1,708,17,2,"4519852,941",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
5,14,16,1,13,1,2025,1,1,2,39,2,6,2,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,7,7,7,7,7,7,0,1,NaN,NaN,6,0,0,1,3,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,6,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,4,1,5,8,42,42,42,1,1,1,708,14,1,"5022058,824",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
6,14,16,1,13,1,2025,1,1,3,19,3,6,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,708,12,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
7,14,26,1,13,2,2025,1,1,1,32,1,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2,8,8,8,8,8,8,8,1,NaN,NaN,8,0,0,7,8,0,0,1,1,2,30,88,4,3200000,5,NaN,3200000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,1,200000,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,8,2,56,56,56,1,1,1,723,12,2,"3214117,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
8,14,26,1,13,2,2025,1,1,2,34,9,1,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,0,0,1,NaN,NaN,8,0,0,11,8,0,0,1,2,1,30,2,4,4000000,5,NaN,4000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,11,2,8,40,40,40,1,1,1,723,17,2,"4017647,059",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
9,14,35,1,13,1,2025,1,1,1,24,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,0,8,8,12,12,12,12,1,NaN,NaN,8,0,0,2,0,2,0,6,NaN,2,88,1,4,2500000,5,NaN,2500000,1,500000,5,300000,6,1,800000,5,NaN,800000,6,NaN,NaN,1,140000,4,NaN,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,2,5,5,64,64,64,1,1,1,437,12,1,"3816764,706",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
10,14,35,1,13,1,2025,1,1,2,27,2,6,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,5,8,0,8,10,10,6,6,1,NaN,NaN,4,0,0,7,4,0,0,1,1,2,12,1,4,2800000,5,NaN,2800000,1,180000,5,2800000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,9,5,48,48,48,1,1,1,437,13,2,"2993147,059",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
11,14,47,1,13,1,2025,1,1,1,40,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,18,0,18,18,0,0,18,1,NaN,NaN,18,0,0,8,18,0,0,1,2,1,30,3,4,5000000,5,NaN,5000000,1,110000,5,5000000,6,1,300000,5,NaN,300000,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,8,5,8,72,72,72,1,1,1,697,13,2,"5433867,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
12,14,50,1,13,1,2025,1,1,1,63,1,6,5,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,2,8,1,7,10,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,405,18,NaN,0,0,0,0,0,0,0,"5524264,706",0,0,0,0,0,0,0,Asunción
13,14,57,1,13,2,2025,1,1,1,71,1,1,1,6,3,6,6,6,NaN,NaN,6,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,8,1,7,11,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
14,14,57,1,13,2,2025,1,1,2,76,2,6,1,6,3,6,6,6,NaN,NaN,6,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
15,14,57,1,13,2,2025,1,1,3,46,3,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,20,2,6,10,4,2,5,5,77,77,77,1,1,1,778,12,2,"1305735,294",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
16,14,57,1,13,2,2025,1,1,4,42,3,6,5,6,3,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,30,2,6,7,5,2,5,5,77,77,77,1,1,1,778,17,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
17,14,66,1,13,2,2025,1,1,1,31,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,"5,3","5,3","5,3","5,3","5,3",0,0,1,NaN,NaN,13,0,0,4,13,0,0,6,NaN,2,88,2,4,10000000,5,NaN,10000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,2,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,2,1,11,2,4,3,8,28,28,28,4,4,1,676,16,1,"10044117,647",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
18,14,66,1,13,2,2025,1,1,4,26,9,6,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,1,1,1,1,1,0,0,1,NaN,NaN,1,0,0,11,1,0,0,6,NaN,2,12,2,4,1750000,5,NaN,1750000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,4,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,11,3,8,5,5,5,1,1,1,676,17,1,"1757720,588",0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción
19,14,66,1,13,2,2025,1,1,5,10,9,1,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,676,2,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Asunción

## Exploring other columns

In [19]:
df['A06E'].value_counts().sort_index()

# ADICTO               1
# ES ADICTO            1
# ES ATLETA DE REMO    1
# ES DROGADICTO        1

# Cuál fue la razón principal por la que no habría podido empezar a trabajar? Otra razón (especificar)

A06E
ADICTO               1
ES ADICTO            1
ES ATLETA DE REMO    1
ES DROGADICTO        1
Name: count, dtype: int64

In [20]:
df['A09E'].value_counts().sort_index()

# CURSILLO PARA POLICIA    1
# NO QUIERE TRABAJAR       2
# PRACTICA DE FUTBOL       1

# Cuál fue la razón principal por la que no buscó trabajo en los últimos 7 días? Otra razón (especificar)

A09E
CURSILLO PARA POLICIA    1
NO QUIERE TRABAJAR       2
PRACTICA DE FUTBOL       1
Name: count, dtype: int64

In [21]:
df['B03LU'].value_counts().sort_index()
df['B03MA'].value_counts().sort_index()
df['B03MI'].value_counts().sort_index()
df['B03JU'].value_counts().sort_index()
df['B03VI'].value_counts().sort_index()
df['B03SA'].value_counts().sort_index()
df['B03DO'].value_counts().sort_index()

# Horas trabajó efectivamente el día ____ (horas, minutos)

B03DO
,3          4
0        4927
1         158
1,15        1
1,3         8
10        129
11          9
12        184
13         13
14         18
15          6
16          6
18          8
2         148
2,3         5
3         154
3,3         1
4         158
4,3         1
5         203
5,3         2
6         181
6,3         2
7          32
8         246
8,3         3
9          70
9,3         2
99,99       3
Name: count, dtype: int64

In [22]:
df['B06'].value_counts().sort_index()

# Horas que trabaja habitualmente en la semana en esta ocupación

B06
10          9
12         11
14          1
15          6
16          2
17,3        1
18          5
20         50
21          3
22          2
24         17
25         15
28          3
3           3
30         71
32          1
33          1
35         10
36         20
38          1
4           3
4,5         1
40        149
42          4
44         12
45         31
46          3
48         51
5           2
50         31
51          1
52          4
54          7
55          8
56          6
57          2
6           3
60         27
65          3
66          3
67          1
7           2
70          2
72         12
8           2
84          2
999,99      3
Name: count, dtype: int64

In [23]:
df['C03'].value_counts().sort_index()

# Cuántas horas trabajó efectivamente en esta ocupación durante los últimos 7 días ?

C03
0      24
1       2
10     81
12     38
13      1
14     17
15     71
16     24
17      2
18     20
2      12
20     85
21     19
22      6
24     24
25     10
27      1
28      7
3      10
3,3     1
30     40
32      1
35     21
36      8
38      1
4      19
4,3     1
40     12
42      2
45      1
48      3
49      3
5      17
50      5
56      1
6      13
7      39
70      2
8      20
8,5     1
9       4
Name: count, dtype: int64

In [24]:
df['C18'].value_counts().sort_index()

# Horas que trabajó efectivamente en estas otras ocupaciones  en los últimos 7 días

C18
10     7
14     2
15     5
18     2
2      3
2,3    1
20     4
21     1
25     2
3      2
30     2
4      1
5      1
7      6
8      1
9      1
Name: count, dtype: int64

In [25]:
df['D02'].value_counts().sort_index()

# Cuántas horas más tuvo disponible para trabajar ?

D02
10        138
12        114
14         22
15         70
16         12
18         36
2           2
20        123
21          6
22          1
24         33
25         20
28          3
3           5
30         37
32          5
35          3
36          6
4           2
40         16
48          3
5           8
50          1
6          11
60          1
7           6
72          1
8          16
9           1
999,99      6
Name: count, dtype: int64

In [26]:
for col_name in df.loc[:, "UPM": "Informalidad"]:
    print(f"Column name: {col_name}")
    print(df[col_name].value_counts().sort_index())
    print("\n")

Column name: UPM
UPM
14       20
102      22
206      25
236      17
266      33
279      13
322      51
366      22
380      25
425      38
485      21
572      61
616      50
646      13
714      37
770      15
783      25
849      35
861      16
873      27
939      20
1008     30
1156     21
1195     25
1316     29
1345     10
1386     33
1428     14
1442     12
1524     17
1638     37
1667     14
1737     36
1824     38
1879     29
2017      6
2086     26
2230     44
2281      9
2320     31
2347     37
2386     38
2424     34
2460     30
2495     26
2513     35
2579     38
2846     34
2867     31
2904     31
2923     39
2948     19
3031     28
3155     30
3207     27
3401     41
3484     29
3504     29
3627     25
3641      8
3678     32
3755     36
3842      9
3964     30
4004     33
4028     27
4059     36
4185     27
4286     27
4390     41
4482     26
4635     33
4664     25
5036     26
5107     25
5189     21
5202     28
5252     20
5329     28
5397     46
5419     44
5466     29
5782     30
5827     31
5878     48
5891     30
5931     41
5990     24
6023     37
6096     28
6121     34
6218     26
6320     20
6339     35
6387     32
6530     32
6585     27
6604     55
6714     29
6738     25
6774     40
6834     29
6907     34
6978     43
7052     34
7118     35
7217     38
7359     30
7373     25
7386     35
7458     41
7553     25
7593     30
7618     22
7634     24
7713     33
7746     30
7803     40
7821     39
7956     25
8053     34
8390     22
8428     43
8502     35
8587     29
8620     60
8676     41
8861     39
8980     45
9115     39
9163     33
9579     29
9659     31
9800     30
9831     28
9992     47
10099    31
10138    18
10199    28
10210    20
10293    25
10325    43
10419    39
10475    25
10515    21
10530    39
10592    42
10668    31
10737    21
10852    32
10898    32
10910    46
10981    54
11015    37
11030    25
11076    28
11135    22
11164    18
11178    21
11207    19
11414    40
11466    41
11501    37
11642    20
11728    36
11743    37
11878    18
11935    26
12299    35
12360    27
12490    12
12505    18
12726    35
12748    35
12784    35
12831    23
12900    31
13062    34
13145    33
13285    31
13321    33
13363    31
13487    32
13514    42
13629    35
13727    40
13755    33
13767    41
13770    34
13786    32
13803    31
13845    40
13866    25
13908    35
13920    36
13933    48
13974    37
14008    28
14082    26
14118    15
14136    28
14154    24
14277    37
14292    32
14320    29
14326    29
14340    43
14386    30
14399    43
14483    27
14497    37
14690    33
14816    28
14843    31
14913    27
14950    32
15010    27
15072    50
15095    35
15127    29
15208    33
15253    24
15451    35
15473    33
15556    37
15684    40
15797    48
15878    25
15910    44
15940    42
16001    56
16017    58
16049    21
16065    24
16157    35
16190    41
16222    20
16268    36
16296    25
16313    38
16356    38
16491    35
16537    40
16659    23
16691    53
16723    35
16945    36
16992    21
17038    27
17224    45
17241    54
17280    37
17294    30
17305    37
17318    39
17380    27
17398    33
17486    31
17547    27
17641    20
17748    37
17842    34
17917    31
18049    31
18073    33
18177    23
18377    39
18428    19
18614    20
18818    11
18977    39
19001    34
19012    33
19106    50
19237    39
19351    26
19398    41
19589    22
19787    33
19930    27
19977    43
20111    27
20135    17
20158    33
20179    33
20201    22
20225    31
20291    21
20475    38
20498    41
20546    68
20574    32
20616    46
20639    32
20941    24
20990    38
21040    36
21089    39
21255    23
21436    29
21586    26
21685    11
21808    42
21832    46
21854    33
21878    31
21927    31
21977    42
22000    38
22070    59
22141    41
22209    26
22302    37
22324    33
22488    45
22583    40
22872    35
22969    33
23359    28
23569    48
23810    36
23933    39
24006    34
24129    28
24226    51
24371    18
24468    34
24563    15
24588    35
24611    23
24850    46
25088    38
25233    28
25282    32
25431    27
25465    31
25577    46
25586    37
25997    49
26102    33
26109    29
26158    29
26165    14
26207    24
26286    27
26364    21
26379    21
26405    26
26412    24
26464    22
26481    25
26499    28
26530    26
26540    35
26548    34
26573    27
26633    20
26686    34
26702    39
26710    41
26732    24
26747    16
26770    43
26803    15
26841    17
26895    27
26958    39
27014    31
27038    31
27073    27
27088    12
27103    18
27120    24
27162    33
27171    33
27210    31
27214    26
27243    37
27252    38
27260    26
27355    44
27392    33
27449    43
27457    40
27516    36
27529    34
27555    32
27569    21
27647    32
27687    32
27770    35
27777    38
27817    42
27873    25
27917    27
27958    22
28025    27
28080    42
28119    49
28156    35
28197    42
28237    25
28265    37
28330    47
28364    33
28371    47
28442    34
28461    48
28506    24
28514    39
28560    21
28570    36
28578    31
28631    27
28663    28
28697    37
28724    32
Name: count, dtype: int64


Column name: NVIVI
NVIVI
1      252
2      190
3      183
4      218
5      255
6      232
7      214
8      244
9      218
10     180
11     192
12     232
13     200
14     193
15     225
16     258
17     214
18     233
19     188
20     257
21     191
22     200
23     175
24     208
25     239
26     173
27     189
28     201
29     191
30     265
31     197
32     194
33     235
34     214
35     179
36     192
37     214
38     187
39     197
40     201
41     221
42     151
43     221
44     144
45     219
46     179
47     198
48     122
49     120
50     153
51     114
52     158
53     129
54     131
55     134
56     118
57     104
58     105
59     144
60     103
61     105
62     105
63      90
64      76
65      92
66      69
67      88
68      38
69      77
70      85
71      76
72      55
73      55
74      61
75      59
76      34
77      35
78      42
79      21
80      30
81      47
82      29
83      39
84      28
85      18
86      19
87      37
88      28
89       9
90      17
91      38
92       8
93      17
94      17
95       9
96      17
97       4
98      26
99       4
100      7
101      5
102      8
103      6
104      9
105      4
106      5
107      1
108      6
110      1
111      9
112      2
113      4
114      5
115      1
118      1
119      3
120      5
121      3
122      2
123      5
124      3
125      5
128      4
133      3
134      3
136      1
137      4
138      2
139      1
149      4
150      1
153      3
154      3
157      5
166      3
168      2
171      4
176      1
177      2
186      1
196      4
198      3
Name: count, dtype: int64


Column name: NHOGA
NHOGA
1    13242
2        4
Name: count, dtype: int64


Column name: TRIMESTRE
TRIMESTRE
13    13246
Name: count, dtype: int64


Column name: RONDA
RONDA
1    6707
2    6539
Name: count, dtype: int64


Column name: ANIO
ANIO
2025    13246
Name: count, dtype: int64


Column name: AREA
AREA
1    7792
6    5454
Name: count, dtype: int64


Column name: ESTGEO
ESTGEO
1       963
11      231
16      273
21      144
26      478
31      293
36      453
41      259
46      343
51      312
56      377
61      122
66      425
71      391
76      556
81      445
86      278
91      223
96      368
101    1122
106     397
111    2022
116     367
121     282
126     163
131     376
136     205
141     371
146     419
151     236
156     352
Name: count, dtype: int64


Column name: L02
L02
1     3881
2     3331
3     2483
4     1704
5      942
6      456
7      222
8      116
9       53
10      27
11      11
12       6
13       4
14       3
15       2
16       1
17       1
18       1
19       1
20       1
Name: count, dtype: int64


Column name: P02
P02
0      134
1      205
2      204
3      198
4      221
5      206
6      217
7      250
8      260
9      210
10     225
11     252
12     223
13     244
14     241
15     208
16     211
17     220
18     212
19     209
20     182
21     196
22     203
23     149
24     208
25     220
26     220
27     222
28     201
29     198
30     222
31     202
32     188
33     180
34     210
35     216
36     174
37     200
38     180
39     166
40     178
41     182
42     186
43     161
44     146
45     167
46     143
47     130
48     125
49     137
50     146
51     150
52     143
53     125
54     142
55     123
56     138
57     115
58     124
59     115
60     131
61     120
62     119
63     137
64     135
65     109
66     113
67     104
68      97
69      98
70     106
71      76
72      69
73      53
74      67
75      56
76      41
77      42
78      48
79      54
80      40
81      38
82      35
83      25
84      29
85      23
86      18
87      23
88      13
89      11
90      14
91       6
92       5
93       8
94       6
95       6
96       2
97       4
98       1
104      1
Name: count, dtype: int64


Column name: P03
P03
1     4039
2     2389
3     4915
4      112
5      927
6      188
7      138
8       36
9      404
10      75
11      21
12       2
Name: count, dtype: int64


Column name: P06
P06
1    6537
6    6709
Name: count, dtype: int64


Column name: P09
P09
1    2924
2    2476
3     518
4     546
5    6714
6      68
Name: count, dtype: int64


Column name: A01
A01
1    5684
6    5457
Name: count, dtype: int64


Column name: A01A
A01A
1     2754
10       1
11       3
12       3
2     1951
3      354
30      12
4      187
5      106
6       50
7       21
8       15
Name: count, dtype: int64


Column name: A02
A02
1    6464
6    4677
Name: count, dtype: int64


Column name: A03
A03
1       6
6    4671
Name: count, dtype: int64


Column name: A04
A04
1     212
6    4459
Name: count, dtype: int64


Column name: A04B
A04B
0      54
1     121
12      1
2      28
3       2
4       3
6       1
9       2
Name: count, dtype: int64


Column name: A04A
A04A
1    6013
2     628
3      41
Name: count, dtype: int64


Column name: A05
A05
1     603
6    3856
Name: count, dtype: int64


Column name: A06
A06
1        4
10      19
11     297
12       4
2        5
3      884
4     1715
5      290
6      341
7      112
8        5
9      180
Name: count, dtype: int64


Column name: A06E
A06E
ADICTO               1
ES ADICTO            1
ES ATLETA DE REMO    1
ES DROGADICTO        1
Name: count, dtype: int64


Column name: A07
A07
1    307
6    296
Name: count, dtype: int64


Column name: A08
A08
1     37
6    259
Name: count, dtype: int64


Column name: A09
A09
1      1
10     8
11    10
12     4
13     1
15     8
16     1
17    39
18     4
2     40
3     10
4     19
6     68
7     48
8      5
9     30
Name: count, dtype: int64


Column name: A09E
A09E
CURSILLO PARA POLICIA    1
NO QUIERE TRABAJAR       2
PRACTICA DE FUTBOL       1
Name: count, dtype: int64


Column name: A10
A10
1    129
2      3
3      1
4    129
5      4
6      5
7      3
8     33
Name: count, dtype: int64


Column name: A11A
A11A
0    286
1     15
2      6
Name: count, dtype: int64


Column name: A11M
A11M
0     68
1     77
11     3
2     72
3     49
4      9
5      5
6     19
7      1
8      4
Name: count, dtype: int64


Column name: A11S
A11S
0    257
1     19
2     31
Name: count, dtype: int64


Column name: A12
A12
1    2216
6    2243
Name: count, dtype: int64


Column name: A13REC
A13REC
1      35
10      5
2     105
3     107
4     106
5     565
6     213
7     212
8      66
9     802
Name: count, dtype: int64


Column name: A14REC
A14REC
1    292
2    180
3     17
4    132
5    566
6     48
7     90
8    891
Name: count, dtype: int64


Column name: A15
A15
1    175
2    738
3     40
4    692
6    510
7     60
8      1
Name: count, dtype: int64


Column name: A16
A16
1     570
10    543
11     64
2     478
3     146
4     128
5      60
6      57
7      80
8      55
9      35
Name: count, dtype: int64


Column name: A17A
A17A
0     709
1     185
10    144
11     12
12     24
13     17
14     27
15     71
16     12
17     14
18      9
19     10
2     161
20     89
21      2
22      8
23      6
24      4
25     32
26      4
27      7
28      5
29      4
3     115
30     51
31      5
32      4
33      2
34      5
35      6
36      3
37      5
38      1
39      3
4      91
40     14
41      1
42      3
43      2
44      1
45      3
46      1
47      1
48      1
49      1
5     134
50     13
55      1
6      69
64      1
7      48
8      54
9      21
Name: count, dtype: int64


Column name: A17M
A17M
0     1524
1      172
10      20
11      13
2      138
3      111
4       68
5       36
6       80
7       14
8       29
9       11
Name: count, dtype: int64


Column name: A17S
A17S
0    2143
1      15
2      58
Name: count, dtype: int64


Column name: A18
A18
1      80
10     78
11    107
12     17
13     33
14    791
15    156
16     13
17    348
18      4
2      13
3      53
4      80
5     100
6       4
7     100
8     191
9      48
Name: count, dtype: int64


Column name: B01REC
B01REC
1      217
10      19
2      513
3      452
4      282
5     1415
6     1166
7      874
8      363
9     1379
99       2
Name: count, dtype: int64


Column name: B02REC
B02REC
1     1426
2      619
3       22
4      524
5     1834
6      220
7      376
8     1659
99       2
Name: count, dtype: int64


Column name: B03LU
B03LU
0         806
1          85
1,15        1
1,3         5
10        691
10,3        3
11         81
11,3        1
12        424
13         24
14         36
15         12
16          4
17          1
18          7
2         163
2,3        20
3         308
3,15        1
3,3         7
4         407
4,3         4
5         412
5,3         7
6         573
6,3         5
7         166
7,3         4
8        1936
8,15        1
8,3        23
8,45        2
9         445
9,3        14
99,99       3
Name: count, dtype: int64


Column name: B03MA
B03MA
,3          1
0         745
1          92
1,15        1
1,3         3
10        709
10,3        3
11         80
11,3        1
12        442
13         26
14         35
15         12
16          4
17          1
18          6
2         170
2,3        20
3         303
3,15        1
3,3         7
4         407
4,3         4
5         385
5,3         6
6         580
6,3         5
7         165
7,3         5
8        1963
8,15        1
8,3        23
8,45        2
9         459
9,3        12
99,99       3
Name: count, dtype: int64


Column name: B03MI
B03MI
,3          1
0         671
1          85
1,15        1
1,3         3
10        716
10,3        3
11         77
11,3        1
12        439
13         24
14         33
15         13
16          5
18          8
2         171
2,3        20
3         312
3,15        1
3,3         8
4         404
4,3         5
5         412
5,3         8
6         593
6,3         5
7         169
7,3         6
8        1988
8,15        1
8,3        21
8,45        2
9         460
9,3        13
99,99       3
Name: count, dtype: int64


Column name: B03JU
B03JU
,3          1
0         673
1          84
1,15        1
1,3         3
10        714
10,3        3
11         78
11,3        1
12        444
13         24
14         33
15         13
16          8
18          6
2         168
2,3        20
3         310
3,15        1
3,3         7
4         423
4,3         3
5         399
5,3         7
6         595
6,3         4
7         167
7,3         4
8        1983
8,15        1
8,3        22
8,45        2
9         464
9,3        13
99,99       3
Name: count, dtype: int64


Column name: B03VI
B03VI
0         601
1          92
1,15        1
1,3         3
10        730
10,3        3
11         78
11,3        1
12        449
12,3        1
13         25
14         33
15         13
16          4
17          1
18          6
2         168
2,3        20
3         326
3,15        1
3,3         9
4         420
4,3         4
5         429
5,3         6
6         596
6,3         5
7         169
7,3         5
8        1979
8,15        1
8,3        22
8,45        2
9         462
9,3        14
99,99       3
Name: count, dtype: int64


Column name: B03SA
B03SA
,3          1
0        2000
1          84
1,15        1
1,3         4
10        409
11         33
11,3        1
12        354
12,3        1
13         22
14         27
15         13
16          4
17          1
18          5
2         175
2,3        17
3         292
3,15        1
3,3         7
4         563
4,3         3
5         754
5,3         7
6         593
6,3         2
7         103
7,3         2
8         964
8,3         8
8,45        1
9         225
9,3         2
99,99       3
Name: count, dtype: int64


Column name: B03DO
B03DO
,3          4
0        4927
1         158
1,15        1
1,3         8
10        129
11          9
12        184
13         13
14         18
15          6
16          6
18          8
2         148
2,3         5
3         154
3,3         1
4         158
4,3         1
5         203
5,3         2
6         181
6,3         2
7          32
8         246
8,3         3
9          70
9,3         2
99,99       3
Name: count, dtype: int64


Column name: B04
B04
1    6075
2      28
3     576
9       3
Name: count, dtype: int64


Column name: B05
B05
1     125
10      2
11     16
12     33
13      4
2       8
3       6
4      14
5       8
6      61
7      24
8     243
9      32
99      3
Name: count, dtype: int64


Column name: B06
B06
10          9
12         11
14          1
15          6
16          2
17,3        1
18          5
20         50
21          3
22          2
24         17
25         15
28          3
3           3
30         71
32          1
33          1
35         10
36         20
38          1
4           3
4,5         1
40        149
42          4
44         12
45         31
46          3
48         51
5           2
50         31
51          1
52          4
54          7
55          8
56          6
57          2
6           3
60         27
65          3
66          3
67          1
7           2
70          2
72         12
8           2
84          2
999,99      3
Name: count, dtype: int64


Column name: B07A
B07A
0     702
1     467
10    406
11     84
12    130
13     99
14     92
15    220
16     67
17     70
18     75
19     40
2     499
20    359
21     35
22     54
23     46
24     46
25    155
26     30
27     45
28     32
29     21
3     417
30    205
31     16
32     25
33     25
34     26
35     74
36     31
37     17
38     23
39     11
4     340
40    133
41     18
42     17
43     25
44     20
45     58
46     16
47     18
48     19
49     12
5     382
50     73
51      8
52      9
53     17
54     11
55     15
56      7
57      9
58     11
59      8
6     241
60     33
61     10
62      5
63      3
64      4
65      5
66      3
67      2
68      3
69      1
7     209
70      6
73      1
76      1
8     196
9      87
99      2
Name: count, dtype: int64


Column name: B07M
B07M
0     5773
1      122
10      32
11      13
2      141
3      137
4       89
5       58
6      171
7       40
8       81
9       23
99       2
Name: count, dtype: int64


Column name: B07S
B07S
0    6638
1      28
2      14
9       2
Name: count, dtype: int64


Column name: B08
B08
1     1525
10     466
11     357
2     2438
3      505
4      377
5      210
6      179
7      252
8      262
9      110
99       1
Name: count, dtype: int64


Column name: B09A
B09A
0     1109
1      585
10     352
11      74
12     118
13      84
14      79
15     189
16      59
17      65
18      55
19      33
2      577
20     296
21      25
22      52
23      36
24      35
25     123
26      25
27      34
28      28
29      16
3      469
30     185
31      16
32      27
33      16
34      22
35      59
36      28
37      18
38      19
39       6
4      364
40     113
41      11
42       9
43      11
44       8
45      39
46       9
47      10
48      13
49       5
5      384
50      38
51       8
52       7
53       5
54       4
55       3
56       3
57       3
58       2
59       1
6      235
60      12
61       2
64       1
65       1
7      198
8      183
9       84
99       2
Name: count, dtype: int64


Column name: B09M
B09M
0     5410
1      201

In [27]:
df['P02'].describe()

count    13246.000000
mean        33.567341
std         22.122773
min          0.000000
25%         15.000000
50%         31.000000
75%         50.000000
max        104.000000
Name: P02, dtype: float64

In [28]:
df['P02'].value_counts().sort_index()

P02
0      134
1      205
2      204
3      198
4      221
5      206
6      217
7      250
8      260
9      210
10     225
11     252
12     223
13     244
14     241
15     208
16     211
17     220
18     212
19     209
20     182
21     196
22     203
23     149
24     208
25     220
26     220
27     222
28     201
29     198
30     222
31     202
32     188
33     180
34     210
35     216
36     174
37     200
38     180
39     166
40     178
41     182
42     186
43     161
44     146
45     167
46     143
47     130
48     125
49     137
50     146
51     150
52     143
53     125
54     142
55     123
56     138
57     115
58     124
59     115
60     131
61     120
62     119
63     137
64     135
65     109
66     113
67     104
68      97
69      98
70     106
71      76
72      69
73      53
74      67
75      56
76      41
77      42
78      48
79      54
80      40
81      38
82      35
83      25
84      29
85      23
86      18
87      23
88      13
89      11
90      14
91       6
92       5
93       8
94       6
95       6
96       2
97       4
98       1
104      1
Name: count, dtype: int64

## Cleaning income columns

Define a list of those 14 column names

Replace 99999999999 with NaN across all of them

Replace any blank strings with NaN

Convert to numeric type

Sum them into a new column INGRESO_TOTAL, using skipna=True

Where all 14 columns are NaN, set INGRESO_TOTAL to NaN

In [29]:
# All E... columns are set as income_cols

income_cols = [
    'E01AIMDE',
    'E01BIMDE',
    'E01CIMDE',
    'E01DDE',
    'E01EDE',
    'E01FDE',
    'E01GDE',
    'E01HDE',
    'E01IDE',
    'E01JDE',
    'E01KDE',
    'E01LDE',
    'E01MDE',
    'E01KJDE'
]

In [30]:
# Replacing local thousands separators by standardized ones.

for col in income_cols:
    df[col] = df[col].str.replace(',', '.')

In [31]:
# Changing income columns to numeric types.

for col in income_cols:
    df[col] = pd.to_numeric(df[col], errors = 'coerce')

df.head(20)

,UPM,NVIVI,NHOGA,TRIMESTRE,RONDA,ANIO,AREA,ESTGEO,L02,P02,P03,P06,P09,A01,A01A,A02,A03,A04,A04B,A04A,A05,A06,A06E,A07,A08,A09,A09E,A10,A11A,A11M,A11S,A12,A13REC,A14REC,A15,A16,A17A,A17M,A17S,A18,B01REC,B02REC,B03LU,B03MA,B03MI,B03JU,B03VI,B03SA,B03DO,B04,B05,B06,B07A,B07M,B07S,B08,B09A,B09M,B09S,B10,B11,B12,B13,B14,B15,B16G,B16U,B16D,B16T,B17,B18AG,B18AU,B18BG,B18BU,B19,B20G,B20U,B20D,B20T,B21,B22,B23,B24,B25,B26,B271,B272,B28,B29,B30,B31,C01REC,C02REC,C03,C04,C05,C06,C07,C08,C09,C101,C102,C11G,C11U,C11D,C11T,C12,C13AG,C13AU,C13BG,C13BU,C14,C14A,C14B,C14C,C15,C16REC,C17REC,C18,C18A,C18B,C19,D01,D02,D03,D04,D05,CATE_PEA,TAMA_PEA,OCUP_PEA,RAMA_PEA,HORAB,HORABC,HORABCO,PEAD,PEAD_1,PEAA,Factor,Añoest,Informalidad,E01AIMDE,E01BIMDE,E01CIMDE,E01DDE,E01EDE,E01FDE,E01GDE,E01HDE,E01IDE,E01JDE,E01KDE,E01LDE,E01MDE,E01KJDE,DPTO,DPTO_NAMES
0,14,13,1,13,1,2025,1,1,1,65,1,1,1,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,3,2,2,8,3,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,381,15,NaN,0.000000e+00,0.0,0.0,6026470.588,0.0,0.000,0.0,6026470.588,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
1,14,13,1,13,1,2025,1,1,2,69,2,6,1,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,8,8,2,NaN,48,50,0,0,6,20,0,0,1,1,2,12,1,4,NaN,5,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,3,2,6,2,8,48,48,48,1,1,1,381,18,2,7.066529e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
2,14,15,1,13,2,2025,1,1,1,78,1,1,1,1,NaN,6,6,6,NaN,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,4,4,1,10,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,6,NaN,0.000000e+00,0.0,0.0,0.000,0.0,3093588.235,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
3,14,15,1,13,2,2025,1,1,2,78,2,6,1,6,1,6,6,6,NaN,NaN,6,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,5,4,1,20,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,12,NaN,0.000000e+00,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
4,14,16,1,13,1,2025,1,1,1,40,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,9,9,9,9,9,0,0,1,NaN,NaN,7,0,0,8,7,0,0,1,1,2,18,2,4,4500000,5,NaN,4500000,1,0,NaN,4500000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,8,3,2,45,45,45,1,1,1,708,17,2,4.519853e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
5,14,16,1,13,1,2025,1,1,2,39,2,6,2,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,7,7,7,7,7,7,0,1,NaN,NaN,6,0,0,1,3,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,6,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,4,1,5,8,42,42,42,1,1,1,708,14,1,5.022059e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
6,14,16,1,13,1,2025,1,1,3,19,3,6,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,708,12,NaN,0.000000e+00,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
7,14,26,1,13,2,2025,1,1,1,32,1,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2,8,8,8,8,8,8,8,1,NaN,NaN,8,0,0,7,8,0,0,1,1,2,30,88,4,3200000,5,NaN,3200000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,1,200000,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,8,2,56,56,56,1,1,1,723,12,2,3.214118e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
8,14,26,1,13,2,2025,1,1,2,34,9,1,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,0,0,1,NaN,NaN,8,0,0,11,8,0,0,1,2,1,30,2,4,4000000,5,NaN,4000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,11,2,8,40,40,40,1,1,1,723,17,2,4.017647e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
9,14,35,1,13,1,2025,1,1,1,24,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,0,8,8,12,12,12,12,1,NaN,NaN,8,0,0,2,0,2,0,6,NaN,2,88,1,4,2500000,5,NaN,2500000,1,500000,5,300000,6,1,800000,5,NaN,800000,6,NaN,NaN,1,140000,4,NaN,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,2,5,5,64,64,64,1,1,1,437,12,1,3.816765e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
10,14,35,1,13,1,2025,1,1,2,27,2,6,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,5,8,0,8,10,10,6,6,1,NaN,NaN,4,0,0,7,4,0,0,1,1,2,12,1,4,2800000,5,NaN,2800000,1,180000,5,2800000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,9,5,48,48,48,1,1,1,437,13,2,2.993147e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
11,14,47,1,13,1,2025,1,1,1,40,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,18,0,18,18,0,0,18,1,NaN,NaN,18,0,0,8,18,0,0,1,2,1,30,3,4,5000000,5,NaN,5000000,1,110000,5,5000000,6,1,300000,5,NaN,300000,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,8,5,8,72,72,72,1,1,1,697,13,2,5.433868e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
12,14,50,1,13,1,2025,1,1,1,63,1,6,5,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,2,8,1,7,10,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,405,18,NaN,0.000000e+00,0.0,0.0,0.000,0.0,0.000,0.0,5524264.706,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
13,14,57,1,13,2,2025,1,1,1,71,1,1,1,6,3,6,6,6,NaN,NaN,6,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,8,1,7,11,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,0.000000e+00,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
14,14,57,1,13,2,2025,1,1,2,76,2,6,1,6,3,6,6,6,NaN,NaN,6,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,0.000000e+00,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
15,14,57,1,13,2,2025,1,1,3,46,3,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,20,2,6,10,4,2,5,5,77,77,77,1,1,1,778,12,2,1.305735e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
16,14,57,1,13,2,2025,1,1,4,42,3,6,5,6,3,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,30,2,6,7,5,2,5,5,77,77,77,1,1,1,778,17,1,0.000000e+00,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
17,14,66,1,13,2,2025,1,1,1,31,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,"5,3","5,3","5,3","5,3","5,3",0,0,1,NaN,NaN,13,0,0,4,13,0,0,6,NaN,2,88,2,4,10000000,5,NaN,10000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,2,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,2,1,11,2,4,3,8,28,28,28,4,4,1,676,16,1,1.004412e+07,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
18,14,66,1,13,2,2025,1,1,4,26,9,6,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,1,1,1,1,1,0,0,1,NaN,NaN,1,0,0,11,1,0,0,6,NaN,2,12,2,4,1750000,5,NaN,1750000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,4,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,11,3,8,5,5,5,1,1,1,676,17,1,1.757721e+06,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción
19,14,66,1,13,2,2025,1,1,5,10,9,1,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,676,2,NaN,0.000000e+00,0.0,0.0,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,NaN,0.0,0.0,0,Asunción

In [32]:
# Verifying if changes applied correctly.

df.dtypes

UPM               int64
NVIVI             int64
NHOGA             int64
TRIMESTRE         int64
RONDA             int64
ANIO              int64
AREA              int64
ESTGEO            int64
L02               int64
P02               int64
P03               int64
P06               int64
P09               int64
A01              object
A01A             object
A02              object
A03              object
A04              object
A04B             object
A04A             object
A05              object
A06              object
A06E             object
A07              object
A08              object
A09              object
A09E             object
A10              object
A11A             object
A11M             object
A11S             object
A12              object
A13REC           object
A14REC           object
A15              object
A16              object
A17A             object
A17M             object
A17S             object
A18              object
B01REC           object
B02REC           object
B03LU            object
B03MA            object
B03MI            object
B03JU            object
B03VI            object
B03SA            object
B03DO            object
B04              object
B05              object
B06              object
B07A             object
B07M             object
B07S             object
B08              object
B09A             object
B09M             object
B09S             object
B10              object
B11              object
B12              object
B13              object
B14              object
B15              object
B16G             object
B16U             object
B16D             object
B16T             object
B17              object
B18AG            object
B18AU            object
B18BG            object
B18BU            object
B19              object
B20G             object
B20U             object
B20D             object
B20T             object
B21              object
B22             float64
B23              object
B24              object
B25              object
B26              object
B271             object
B272             object
B28              object
B29              object
B30              object
B31              object
C01REC           object
C02REC           object
C03              object
C04              object
C05              object
C06              object
C07              object
C08              object
C09              object
C101             object
C102             object
C11G             object
C11U             object
C11D             object
C11T             object
C12              object
C13AG            object
C13AU            object
C13BG            object
C13BU            object
C14              object
C14A             object
C14B             object
C14C             object
C15              object
C16REC           object
C17REC           object
C18              object
C18A             object
C18B            float64
C19              object
D01              object
D02              object
D03              object
D04              object
D05              object
CATE_PEA         object
TAMA_PEA         object
OCUP_PEA         object
RAMA_PEA         object
HORAB            object
HORABC           object
HORABCO          object
PEAD             object
PEAD_1           object
PEAA             object
Factor            int64
Añoest           object
Informalidad     object
E01AIMDE        float64
E01BIMDE        float64
E01CIMDE        float64
E01DDE          float64
E01EDE          float64
E01FDE          float64
E01GDE          float64
E01HDE          float64
E01IDE          float64
E01JDE          float64
E01KDE          float64
E01LDE          float64
E01MDE          float64
E01KJDE         float64
DPTO              int64
DPTO_NAMES       object
dtype: object

In [33]:
# Verifying that there are no longer sentinel values.

print((df[income_cols] == 99999999999).sum())
print("\n")
print((df[income_cols] == "99999999999").sum())

E01AIMDE    0
E01BIMDE    0
E01CIMDE    0
E01DDE      0
E01EDE      0
E01FDE      0
E01GDE      0
E01HDE      0
E01IDE      0
E01JDE      0
E01KDE      0
E01LDE      0
E01MDE      0
E01KJDE     0
dtype: int64


E01AIMDE    0
E01BIMDE    0
E01CIMDE    0
E01DDE      0
E01EDE      0
E01FDE      0
E01GDE      0
E01HDE      0
E01IDE      0
E01JDE      0
E01KDE      0
E01LDE      0
E01MDE      0
E01KJDE     0
dtype: int64

In [34]:
# Replacing 0s with NaN in income columns

df[income_cols] = df[income_cols].replace(0, np.nan)

In [35]:
# Creating a total_income column to sum all types of income

df['TOTAL_INCOME'] = df[income_cols].sum(axis = 1)

/var/folders/_2/rdn49_x54gj8wdryd0q1lxzr0000gn/T/ipykernel_5750/1308467989.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['TOTAL_INCOME'] = df[income_cols].sum(axis = 1)

## Income columns verifications

In [36]:
df.head(20)

,UPM,NVIVI,NHOGA,TRIMESTRE,RONDA,ANIO,AREA,ESTGEO,L02,P02,P03,P06,P09,A01,A01A,A02,A03,A04,A04B,A04A,A05,A06,A06E,A07,A08,A09,A09E,A10,A11A,A11M,A11S,A12,A13REC,A14REC,A15,A16,A17A,A17M,A17S,A18,B01REC,B02REC,B03LU,B03MA,B03MI,B03JU,B03VI,B03SA,B03DO,B04,B05,B06,B07A,B07M,B07S,B08,B09A,B09M,B09S,B10,B11,B12,B13,B14,B15,B16G,B16U,B16D,B16T,B17,B18AG,B18AU,B18BG,B18BU,B19,B20G,B20U,B20D,B20T,B21,B22,B23,B24,B25,B26,B271,B272,B28,B29,B30,B31,C01REC,C02REC,C03,C04,C05,C06,C07,C08,C09,C101,C102,C11G,C11U,C11D,C11T,C12,C13AG,C13AU,C13BG,C13BU,C14,C14A,C14B,C14C,C15,C16REC,C17REC,C18,C18A,C18B,C19,D01,D02,D03,D04,D05,CATE_PEA,TAMA_PEA,OCUP_PEA,RAMA_PEA,HORAB,HORABC,HORABCO,PEAD,PEAD_1,PEAA,Factor,Añoest,Informalidad,E01AIMDE,E01BIMDE,E01CIMDE,E01DDE,E01EDE,E01FDE,E01GDE,E01HDE,E01IDE,E01JDE,E01KDE,E01LDE,E01MDE,E01KJDE,DPTO,DPTO_NAMES,TOTAL_INCOME
0,14,13,1,13,1,2025,1,1,1,65,1,1,1,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,3,2,2,8,3,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,381,15,NaN,NaN,NaN,NaN,6026470.588,NaN,NaN,NaN,6026470.588,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.205294e+07
1,14,13,1,13,1,2025,1,1,2,69,2,6,1,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,8,8,2,NaN,48,50,0,0,6,20,0,0,1,1,2,12,1,4,NaN,5,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,3,2,6,2,8,48,48,48,1,1,1,381,18,2,7.066529e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,7.066529e+06
2,14,15,1,13,2,2025,1,1,1,78,1,1,1,1,NaN,6,6,6,NaN,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,4,4,1,10,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,6,NaN,NaN,NaN,NaN,NaN,NaN,3093588.235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,3.093588e+06
3,14,15,1,13,2,2025,1,1,2,78,2,6,1,6,1,6,6,6,NaN,NaN,6,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,5,4,1,20,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,0.000000e+00
4,14,16,1,13,1,2025,1,1,1,40,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,9,9,9,9,9,0,0,1,NaN,NaN,7,0,0,8,7,0,0,1,1,2,18,2,4,4500000,5,NaN,4500000,1,0,NaN,4500000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,8,3,2,45,45,45,1,1,1,708,17,2,4.519853e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,4.519853e+06
5,14,16,1,13,1,2025,1,1,2,39,2,6,2,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,7,7,7,7,7,7,0,1,NaN,NaN,6,0,0,1,3,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,6,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,4,1,5,8,42,42,42,1,1,1,708,14,1,5.022059e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,5.022059e+06
6,14,16,1,13,1,2025,1,1,3,19,3,6,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,708,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,0.000000e+00
7,14,26,1,13,2,2025,1,1,1,32,1,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2,8,8,8,8,8,8,8,1,NaN,NaN,8,0,0,7,8,0,0,1,1,2,30,88,4,3200000,5,NaN,3200000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,1,200000,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,8,2,56,56,56,1,1,1,723,12,2,3.214118e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,3.214118e+06
8,14,26,1,13,2,2025,1,1,2,34,9,1,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,0,0,1,NaN,NaN,8,0,0,11,8,0,0,1,2,1,30,2,4,4000000,5,NaN,4000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,11,2,8,40,40,40,1,1,1,723,17,2,4.017647e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,4.017647e+06
9,14,35,1,13,1,2025,1,1,1,24,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,0,8,8,12,12,12,12,1,NaN,NaN,8,0,0,2,0,2,0,6,NaN,2,88,1,4,2500000,5,NaN,2500000,1,500000,5,300000,6,1,800000,5,NaN,800000,6,NaN,NaN,1,140000,4,NaN,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,2,5,5,64,64,64,1,1,1,437,12,1,3.816765e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,3.816765e+06
10,14,35,1,13,1,2025,1,1,2,27,2,6,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,5,8,0,8,10,10,6,6,1,NaN,NaN,4,0,0,7,4,0,0,1,1,2,12,1,4,2800000,5,NaN,2800000,1,180000,5,2800000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,9,5,48,48,48,1,1,1,437,13,2,2.993147e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,2.993147e+06
11,14,47,1,13,1,2025,1,1,1,40,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,18,0,18,18,0,0,18,1,NaN,NaN,18,0,0,8,18,0,0,1,2,1,30,3,4,5000000,5,NaN,5000000,1,110000,5,5000000,6,1,300000,5,NaN,300000,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,8,5,8,72,72,72,1,1,1,697,13,2,5.433868e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,5.433868e+06
12,14,50,1,13,1,2025,1,1,1,63,1,6,5,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,2,8,1,7,10,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,405,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5524264.706,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,5.524265e+06
13,14,57,1,13,2,2025,1,1,1,71,1,1,1,6,3,6,6,6,NaN,NaN,6,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,8,1,7,11,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,0.000000e+00
14,14,57,1,13,2,2025,1,1,2,76,2,6,1,6,3,6,6,6,NaN,NaN,6,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,0.000000e+00
15,14,57,1,13,2,2025,1,1,3,46,3,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,20,2,6,10,4,2,5,5,77,77,77,1,1,1,778,12,2,1.305735e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.305735e+06
16,14,57,1,13,2,2025,1,1,4,42,3,6,5,6,3,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,30,2,6,7,5,2,5,5,77,77,77,1,1,1,778,17,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,0.000000e+00
17,14,66,1,13,2,2025,1,1,1,31,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,"5,3","5,3","5,3","5,3","5,3",0,0,1,NaN,NaN,13,0,0,4,13,0,0,6,NaN,2,88,2,4,10000000,5,NaN,10000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,2,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,2,1,11,2,4,3,8,28,28,28,4,4,1,676,16,1,1.004412e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.004412e+07
18,14,66,1,13,2,2025,1,1,4,26,9,6,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,1,1,1,1,1,0,0,1,NaN,NaN,1,0,0,11,1,0,0,6,NaN,2,12,2,4,1750000,5,NaN,1750000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,4,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,11,3,8,5,5,5,1,1,1,676,17,1,1.757721e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.757721e+06
19,14,66,1,13,2,2025,1,1,5,10,9,1,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,676,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,0.000000e+00

In [37]:
# Verifying NaN values, sum should amount to total rows.

df[income_cols].isna().all(axis = 1).value_counts()

False    7608
True     5638
Name: count, dtype: int64

In [38]:
# Verifying amount of NA and 0 values for all cells in income columns.

print(df[income_cols].isna().sum().sum())
print((df[income_cols] == 0).sum().sum())

175626
0

In [39]:
# Creating a mask for income columns where all of their values are NaN. Then applying that mask to the df, and setting the total_income values to NaN when the mask applies (no income in any column whatsoever).

all_nan_mask = df[income_cols].isna().all(axis = 1)
df.loc[all_nan_mask, 'TOTAL_INCOME'] = np.nan

In [40]:
# Verifying the change made, total_income should have all previous 0 values set to NaN and no 0 as the total left.

print(df['TOTAL_INCOME'].isna().sum())  # should be 5638
print((df['TOTAL_INCOME'] == 0).sum())  # should be 0

5638
0

In [41]:
df.head(20)

,UPM,NVIVI,NHOGA,TRIMESTRE,RONDA,ANIO,AREA,ESTGEO,L02,P02,P03,P06,P09,A01,A01A,A02,A03,A04,A04B,A04A,A05,A06,A06E,A07,A08,A09,A09E,A10,A11A,A11M,A11S,A12,A13REC,A14REC,A15,A16,A17A,A17M,A17S,A18,B01REC,B02REC,B03LU,B03MA,B03MI,B03JU,B03VI,B03SA,B03DO,B04,B05,B06,B07A,B07M,B07S,B08,B09A,B09M,B09S,B10,B11,B12,B13,B14,B15,B16G,B16U,B16D,B16T,B17,B18AG,B18AU,B18BG,B18BU,B19,B20G,B20U,B20D,B20T,B21,B22,B23,B24,B25,B26,B271,B272,B28,B29,B30,B31,C01REC,C02REC,C03,C04,C05,C06,C07,C08,C09,C101,C102,C11G,C11U,C11D,C11T,C12,C13AG,C13AU,C13BG,C13BU,C14,C14A,C14B,C14C,C15,C16REC,C17REC,C18,C18A,C18B,C19,D01,D02,D03,D04,D05,CATE_PEA,TAMA_PEA,OCUP_PEA,RAMA_PEA,HORAB,HORABC,HORABCO,PEAD,PEAD_1,PEAA,Factor,Añoest,Informalidad,E01AIMDE,E01BIMDE,E01CIMDE,E01DDE,E01EDE,E01FDE,E01GDE,E01HDE,E01IDE,E01JDE,E01KDE,E01LDE,E01MDE,E01KJDE,DPTO,DPTO_NAMES,TOTAL_INCOME
0,14,13,1,13,1,2025,1,1,1,65,1,1,1,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,3,2,2,8,3,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,381,15,NaN,NaN,NaN,NaN,6026470.588,NaN,NaN,NaN,6026470.588,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.205294e+07
1,14,13,1,13,1,2025,1,1,2,69,2,6,1,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,8,8,2,NaN,48,50,0,0,6,20,0,0,1,1,2,12,1,4,NaN,5,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,3,2,6,2,8,48,48,48,1,1,1,381,18,2,7.066529e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,7.066529e+06
2,14,15,1,13,2,2025,1,1,1,78,1,1,1,1,NaN,6,6,6,NaN,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,4,4,1,10,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,6,NaN,NaN,NaN,NaN,NaN,NaN,3093588.235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,3.093588e+06
3,14,15,1,13,2,2025,1,1,2,78,2,6,1,6,1,6,6,6,NaN,NaN,6,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,5,4,1,20,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,NaN
4,14,16,1,13,1,2025,1,1,1,40,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,9,9,9,9,9,0,0,1,NaN,NaN,7,0,0,8,7,0,0,1,1,2,18,2,4,4500000,5,NaN,4500000,1,0,NaN,4500000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,8,3,2,45,45,45,1,1,1,708,17,2,4.519853e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,4.519853e+06
5,14,16,1,13,1,2025,1,1,2,39,2,6,2,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,7,7,7,7,7,7,0,1,NaN,NaN,6,0,0,1,3,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,6,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,4,1,5,8,42,42,42,1,1,1,708,14,1,5.022059e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,5.022059e+06
6,14,16,1,13,1,2025,1,1,3,19,3,6,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,708,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,NaN
7,14,26,1,13,2,2025,1,1,1,32,1,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2,8,8,8,8,8,8,8,1,NaN,NaN,8,0,0,7,8,0,0,1,1,2,30,88,4,3200000,5,NaN,3200000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,1,200000,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,8,2,56,56,56,1,1,1,723,12,2,3.214118e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,3.214118e+06
8,14,26,1,13,2,2025,1,1,2,34,9,1,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,0,0,1,NaN,NaN,8,0,0,11,8,0,0,1,2,1,30,2,4,4000000,5,NaN,4000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,11,2,8,40,40,40,1,1,1,723,17,2,4.017647e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,4.017647e+06
9,14,35,1,13,1,2025,1,1,1,24,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,0,8,8,12,12,12,12,1,NaN,NaN,8,0,0,2,0,2,0,6,NaN,2,88,1,4,2500000,5,NaN,2500000,1,500000,5,300000,6,1,800000,5,NaN,800000,6,NaN,NaN,1,140000,4,NaN,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,2,5,5,64,64,64,1,1,1,437,12,1,3.816765e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,3.816765e+06
10,14,35,1,13,1,2025,1,1,2,27,2,6,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,5,8,0,8,10,10,6,6,1,NaN,NaN,4,0,0,7,4,0,0,1,1,2,12,1,4,2800000,5,NaN,2800000,1,180000,5,2800000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,7,9,5,48,48,48,1,1,1,437,13,2,2.993147e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,2.993147e+06
11,14,47,1,13,1,2025,1,1,1,40,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,8,18,0,18,18,0,0,18,1,NaN,NaN,18,0,0,8,18,0,0,1,2,1,30,3,4,5000000,5,NaN,5000000,1,110000,5,5000000,6,1,300000,5,NaN,300000,6,NaN,NaN,6,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,1,8,5,8,72,72,72,1,1,1,697,13,2,5.433868e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,5.433868e+06
12,14,50,1,13,1,2025,1,1,1,63,1,6,5,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,2,8,1,7,10,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,405,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5524264.706,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,5.524265e+06
13,14,57,1,13,2,2025,1,1,1,71,1,1,1,6,3,6,6,6,NaN,NaN,6,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,8,1,7,11,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,NaN
14,14,57,1,13,2,2025,1,1,2,76,2,6,1,6,3,6,6,6,NaN,NaN,6,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,778,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,NaN
15,14,57,1,13,2,2025,1,1,3,46,3,1,5,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,1,1,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,20,2,6,10,4,2,5,5,77,77,77,1,1,1,778,12,2,1.305735e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.305735e+06
16,14,57,1,13,2,2025,1,1,4,42,3,6,5,6,3,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,12,12,12,12,12,12,5,1,NaN,NaN,25,0,0,2,25,0,0,6,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,30,2,6,7,5,2,5,5,77,77,77,1,1,1,778,17,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,NaN
17,14,66,1,13,2,2025,1,1,1,31,1,1,3,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,"5,3","5,3","5,3","5,3","5,3",0,0,1,NaN,NaN,13,0,0,4,13,0,0,6,NaN,2,88,2,4,10000000,5,NaN,10000000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,2,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,2,1,11,2,4,3,8,28,28,28,4,4,1,676,16,1,1.004412e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.004412e+07
18,14,66,1,13,2,2025,1,1,4,26,9,6,5,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,1,1,1,1,1,0,0,1,NaN,NaN,1,0,0,11,1,0,0,6,NaN,2,12,2,4,1750000,5,NaN,1750000,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,4,NaN,NaN,1,5,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,11,3,8,5,5,5,1,1,1,676,17,1,1.757721e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.757721e+06
19,14,66,1,13,2,2025,1,1,5,10,9,1,5,6,1,6,6,6,NaN,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,676,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,NaN

## Filtering for working age population

In [42]:
# The standard INE uses for the EPHC is 15 years old, that's also the international ILO standard for labor force surveys.

df_workingage = df[df['P02'] >= 15].copy()
df_workingage.shape

(9956, 157)

In [43]:
df_workingage.head()

,UPM,NVIVI,NHOGA,TRIMESTRE,RONDA,ANIO,AREA,ESTGEO,L02,P02,P03,P06,P09,A01,A01A,A02,A03,A04,A04B,A04A,A05,A06,A06E,A07,A08,A09,A09E,A10,A11A,A11M,A11S,A12,A13REC,A14REC,A15,A16,A17A,A17M,A17S,A18,B01REC,B02REC,B03LU,B03MA,B03MI,B03JU,B03VI,B03SA,B03DO,B04,B05,B06,B07A,B07M,B07S,B08,B09A,B09M,B09S,B10,B11,B12,B13,B14,B15,B16G,B16U,B16D,B16T,B17,B18AG,B18AU,B18BG,B18BU,B19,B20G,B20U,B20D,B20T,B21,B22,B23,B24,B25,B26,B271,B272,B28,B29,B30,B31,C01REC,C02REC,C03,C04,C05,C06,C07,C08,C09,C101,C102,C11G,C11U,C11D,C11T,C12,C13AG,C13AU,C13BG,C13BU,C14,C14A,C14B,C14C,C15,C16REC,C17REC,C18,C18A,C18B,C19,D01,D02,D03,D04,D05,CATE_PEA,TAMA_PEA,OCUP_PEA,RAMA_PEA,HORAB,HORABC,HORABCO,PEAD,PEAD_1,PEAA,Factor,Añoest,Informalidad,E01AIMDE,E01BIMDE,E01CIMDE,E01DDE,E01EDE,E01FDE,E01GDE,E01HDE,E01IDE,E01JDE,E01KDE,E01LDE,E01MDE,E01KJDE,DPTO,DPTO_NAMES,TOTAL_INCOME
0,14,13,1,13,1,2025,1,1,1,65,1,1,1,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,3,2,2,8,3,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,381,15,NaN,NaN,NaN,NaN,6026470.588,NaN,NaN,NaN,6026470.588,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.205294e+07
1,14,13,1,13,1,2025,1,1,2,69,2,6,1,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,8,8,2,NaN,48,50,0,0,6,20,0,0,1,1,2,12,1,4,NaN,5,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,3,2,6,2,8,48,48,48,1,1,1,381,18,2,7066529.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,7.066529e+06
2,14,15,1,13,2,2025,1,1,1,78,1,1,1,1,NaN,6,6,6,NaN,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,4,4,1,10,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,6,NaN,NaN,NaN,NaN,NaN,NaN,3093588.235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,3.093588e+06
3,14,15,1,13,2,2025,1,1,2,78,2,6,1,6,1,6,6,6,NaN,NaN,6,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,5,4,1,20,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,NaN
4,14,16,1,13,1,2025,1,1,1,40,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,9,9,9,9,9,0,0,1,NaN,NaN,7,0,0,8,7,0,0,1,1,2,18,2,4,4500000,5,NaN,4500000,1,0,NaN,4500000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,8,3,2,45,45,45,1,1,1,708,17,2,4519852.941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,4.519853e+06

In [44]:
# df_workingage[df_workingage['PEAA'] == '1'].groupby('DPTO_NAMES')['TOTAL_INCOME'].sum()

# Validating logic for calculating employment rate, testing for Asuncion first.

asuncion_peaa_1 = df_workingage.loc[(df_workingage['DPTO'] == 0) & (df_workingage['PEAA'] == '1'), 'Factor'].sum()
asuncion_peaa_1_2 = df_workingage.loc[(df_workingage['DPTO'] == 0) & ((df_workingage['PEAA'] == '1') | (df_workingage['PEAA'] == '2')), 'Factor'].sum()

print(asuncion_peaa_1 / asuncion_peaa_1_2 * 100.0)

93.84398125502943

In [45]:
# With logic validated, expanding the calculation for the other departments.

emp_rate = df_workingage[df_workingage['PEAA'] == '1'].groupby('DPTO_NAMES')['Factor'].sum() / df_workingage[(df_workingage['PEAA'] == '1') | (df_workingage['PEAA'] == '2')].groupby('DPTO_NAMES')['Factor'].sum() * 100.0
emp_rate

DPTO_NAMES
Alto Paraná    93.564759
Amambay        94.082044
Asunción       93.843981
Caaguazú       93.722435
Caazapá        96.515169
Canindeyú      98.264649
Central        93.594805
Concepción     94.501322
Cordillera     94.478493
Guairá         94.600980
Itapúa         96.104593
Misiones       94.279650
Paraguarí      94.765346
Pdte Hayes     93.757461
San Pedro      98.470991
Ñeembucú       96.006580
Name: Factor, dtype: float64

In [46]:
# Calculating the weighted average income by department: starting with creating an intermediate column that multiplies total_income * factor

df_workingage['TOTAL_INCOME_BY_FACTOR'] = df_workingage['TOTAL_INCOME'] * df_workingage['Factor']
df_workingage.head()

,UPM,NVIVI,NHOGA,TRIMESTRE,RONDA,ANIO,AREA,ESTGEO,L02,P02,P03,P06,P09,A01,A01A,A02,A03,A04,A04B,A04A,A05,A06,A06E,A07,A08,A09,A09E,A10,A11A,A11M,A11S,A12,A13REC,A14REC,A15,A16,A17A,A17M,A17S,A18,B01REC,B02REC,B03LU,B03MA,B03MI,B03JU,B03VI,B03SA,B03DO,B04,B05,B06,B07A,B07M,B07S,B08,B09A,B09M,B09S,B10,B11,B12,B13,B14,B15,B16G,B16U,B16D,B16T,B17,B18AG,B18AU,B18BG,B18BU,B19,B20G,B20U,B20D,B20T,B21,B22,B23,B24,B25,B26,B271,B272,B28,B29,B30,B31,C01REC,C02REC,C03,C04,C05,C06,C07,C08,C09,C101,C102,C11G,C11U,C11D,C11T,C12,C13AG,C13AU,C13BG,C13BU,C14,C14A,C14B,C14C,C15,C16REC,C17REC,C18,C18A,C18B,C19,D01,D02,D03,D04,D05,CATE_PEA,TAMA_PEA,OCUP_PEA,RAMA_PEA,HORAB,HORABC,HORABCO,PEAD,PEAD_1,PEAA,Factor,Añoest,Informalidad,E01AIMDE,E01BIMDE,E01CIMDE,E01DDE,E01EDE,E01FDE,E01GDE,E01HDE,E01IDE,E01JDE,E01KDE,E01LDE,E01MDE,E01KJDE,DPTO,DPTO_NAMES,TOTAL_INCOME,TOTAL_INCOME_BY_FACTOR
0,14,13,1,13,1,2025,1,1,1,65,1,1,1,1,NaN,6,6,6,NaN,NaN,1,NaN,NaN,6,6,15,NaN,NaN,NaN,NaN,NaN,1,3,2,2,8,3,0,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,381,15,NaN,NaN,NaN,NaN,6026470.588,NaN,NaN,NaN,6026470.588,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,1.205294e+07,4.592171e+09
1,14,13,1,13,1,2025,1,1,2,69,2,6,1,6,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,8,8,8,8,8,8,8,8,2,NaN,48,50,0,0,6,20,0,0,1,1,2,12,1,4,NaN,5,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,1,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,3,2,6,2,8,48,48,48,1,1,1,381,18,2,7066529.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,7.066529e+06,2.692348e+09
2,14,15,1,13,2,2025,1,1,1,78,1,1,1,1,NaN,6,6,6,NaN,NaN,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,4,4,1,10,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,6,NaN,NaN,NaN,NaN,NaN,NaN,3093588.235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,3.093588e+06,1.450893e+09
3,14,15,1,13,2,2025,1,1,2,78,2,6,1,6,1,6,6,6,NaN,NaN,6,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,5,4,1,20,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,469,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,NaN,NaN
4,14,16,1,13,1,2025,1,1,1,40,1,1,2,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,9,9,9,9,9,0,0,1,NaN,NaN,7,0,0,8,7,0,0,1,1,2,18,2,4,4500000,5,NaN,4500000,1,0,NaN,4500000,6,6,NaN,NaN,NaN,NaN,6,NaN,NaN,6,NaN,3,NaN,NaN,1,2,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,6,NaN,NaN,2,8,3,2,45,45,45,1,1,1,708,17,2,4519852.941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Asunción,4.519853e+06,3.200056e+09

In [47]:
avg_income = df_workingage[df_workingage['PEAA'] == '1'].groupby('DPTO_NAMES')['TOTAL_INCOME_BY_FACTOR'].sum() / df_workingage[df_workingage['PEAA'] == '1'].groupby('DPTO_NAMES')['Factor'].sum()
avg_income

DPTO_NAMES
Alto Paraná    3.821016e+06
Amambay        3.666521e+06
Asunción       4.470587e+06
Caaguazú       2.580724e+06
Caazapá        2.555354e+06
Canindeyú      2.608296e+06
Central        3.899527e+06
Concepción     3.036613e+06
Cordillera     2.860801e+06
Guairá         2.643181e+06
Itapúa         2.851637e+06
Misiones       2.862608e+06
Paraguarí      2.578897e+06
Pdte Hayes     4.572796e+06
San Pedro      3.175367e+06
Ñeembucú       2.409267e+06
dtype: float64

In [48]:
URBAN_POVERTY_THRESHOLD = 897168
RURAL_POVERTY_THRESHOLD = 654657

For poverty headcount the logic is:

1. For each person (row), check if TOTAL_INCOME is below the poverty line threshold
2. If yes, that person is poor
3. To get the weighted count of poor people, sum their Factor values
4. Divide by total Factor in that department to get the poverty rate

In [49]:
is_poor_urban_mask = (df_workingage['AREA'] == 1) & (df_workingage['TOTAL_INCOME'] < URBAN_POVERTY_THRESHOLD)
print(is_poor_urban_mask.value_counts())
is_poor_rural_mask = (df_workingage['AREA'] == 6) & (df_workingage['TOTAL_INCOME'] < RURAL_POVERTY_THRESHOLD)
print(is_poor_rural_mask.value_counts())
is_poor_mask = is_poor_rural_mask | is_poor_urban_mask
print(is_poor_mask.value_counts())

False    9273
True      683
Name: count, dtype: int64
False    9315
True      641
Name: count, dtype: int64
False    8632
True     1324
Name: count, dtype: int64

In [50]:
poverty_headcount = (df_workingage.loc[is_poor_mask].groupby('DPTO_NAMES')['Factor'].sum() / df_workingage.groupby('DPTO_NAMES')['Factor'].sum() * 100.0).sort_values(ascending = False)
poverty_headcount

DPTO_NAMES
Caaguazú       19.730116
Concepción     18.613671
Ñeembucú       18.209328
Caazapá        17.554398
Guairá         15.628919
Paraguarí      15.382714
San Pedro      15.152730
Misiones       14.560592
Itapúa         14.315985
Canindeyú      12.694471
Amambay        10.968234
Cordillera     10.458496
Pdte Hayes      9.821715
Alto Paraná     9.400607
Central         8.202823
Asunción        3.898481
Name: Factor, dtype: float64

In [51]:
emp_inc_pov = pd.concat([emp_rate, avg_income, poverty_headcount], axis = 1)
emp_inc_pov.columns = ['Employment Rate', 'Average Income', 'Poverty Headcount']
emp_inc_pov.sort_values(by = ['Poverty Headcount'], ascending = False)

             Employment Rate  Average Income  Poverty Headcount
DPTO_NAMES
Caaguazú           93.722435    2.580724e+06          19.730116
Concepción         94.501322    3.036613e+06          18.613671
Ñeembucú           96.006580    2.409267e+06          18.209328
Caazapá            96.515169    2.555354e+06          17.554398
Guairá             94.600980    2.643181e+06          15.628919
Paraguarí          94.765346    2.578897e+06          15.382714
San Pedro          98.470991    3.175367e+06          15.152730
Misiones           94.279650    2.862608e+06          14.560592
Itapúa             96.104593    2.851637e+06          14.315985
Canindeyú          98.264649    2.608296e+06          12.694471
Amambay            94.082044    3.666521e+06          10.968234
Cordillera         94.478493    2.860801e+06          10.458496
Pdte Hayes         93.757461    4.572796e+06           9.821715
Alto Paraná        93.564759    3.821016e+06           9.400607
Central            93.594805    3.899527e+06           8.202823
Asunción           93.843981    4.470587e+06           3.898481

In [57]:
for row in emp_inc_pov.itertuples(index = True, name="arow"):
    print(row)

arow(Index='Alto Paraná', _1=93.56475868818583, _2=3821015.769513659, _3=9.40060699403709)
arow(Index='Amambay', _1=94.08204350554279, _2=3666521.25492148, _3=10.96823379923761)
arow(Index='Asunción', _1=93.84398125502943, _2=4470587.277293192, _3=3.8984806339065923)
arow(Index='Caaguazú', _1=93.72243484599963, _2=2580723.8692043535, _3=19.73011574777197)
arow(Index='Caazapá', _1=96.51516949487757, _2=2555354.274522541, _3=17.554397851605128)
arow(Index='Canindeyú', _1=98.26464906632324, _2=2608295.5148298224, _3=12.694471109982782)
arow(Index='Central', _1=93.5948049964267, _2=3899526.810370379, _3=8.202822886236001)
arow(Index='Concepción', _1=94.501321505605, _2=3036613.08485028, _3=18.613670746802367)
arow(Index='Cordillera', _1=94.47849311217318, _2=2860800.5262954975, _3=10.458496486989363)
arow(Index='Guairá', _1=94.60097971148654, _2=2643181.126220488, _3=15.628918549892717)
arow(Index='Itapúa', _1=96.10459298947777, _2=2851636.8760618297, _3=14.315985216793164)
arow(Index='Misiones', _1=94.27965047835386, _2=2862608.3346813284, _3=14.560591821489673)
arow(Index='Paraguarí', _1=94.76534619729928, _2=2578896.7642993527, _3=15.382713858323616)
arow(Index='Pdte Hayes', _1=93.75746139330688, _2=4572796.115616385, _3=9.821715274966145)
arow(Index='San Pedro', _1=98.47099071423584, _2=3175366.898243624, _3=15.152730408736174)
arow(Index='Ñeembucú', _1=96.00657994415705, _2=2409266.7296691313, _3=18.209327717984714)